# Apache Spark Practice Notebook
##### ลองฝึก PySpark ตัวอย่างข้อมูล Food.com Recipes and Reviews Dataset

Dataset:
`irkaal/foodcom-recipes-and-reviews`

สิ่งที่ได้ฝึก
- โหลด dataset
- SparkSession
- อ่าน CSV
- ดูข้อมูลด้วย `show`, `head`, `first`, `take`
- เช็ก schema / data type / columns
- เลือก column
- แปลงชนิดข้อมูล
- clean missing values และ duplicates
- ใช้ `select`, `when`, `like`, `contains`, `startswith`, `endswith`, `substr`, `between`
- ใช้ `groupBy`, `agg`, `filter`, `sort`, `orderBy`
- join DataFrame
- ใช้ Spark SQL
- save output เป็น Parquet / CSV / JSON

## 0. ติดตั้งและดาวน์โหลด Dataset

In [111]:
import kagglehub

dataset_path = kagglehub.dataset_download(
    "irkaal/foodcom-recipes-and-reviews"
)

print(dataset_path)

Using Colab cache for faster access to the 'foodcom-recipes-and-reviews' dataset.
/kaggle/input/foodcom-recipes-and-reviews


- `import kagglehub`  
  เรียกใช้ package สำหรับดาวน์โหลด dataset จาก Kaggle

- `kagglehub.dataset_download(...)`  
  ดาวน์โหลด dataset ตามชื่อ dataset slug

- `"irkaal/foodcom-recipes-and-reviews"`  
  คือชื่อ dataset ที่ต้องการโหลด

- `dataset_path`  
  คือ path ของ folder ที่เก็บไฟล์หลัง download เสร็จ

In [112]:
#  ===== วิธีโหลดไฟล์ใน Spark =====

#  1) RDD (low-level)
    # from pyspark import SparkContext
    # sc = SparkContext.getOrCreate()

    # rdd_txt = sc.textFile("file.txt")
    # rdd_csv = sc.textFile("file.csv")

# 2) DataFrame
  # JSON
  # df_json = spark.read.json("file.json")

  # Parquet
  # df_parquet = spark.read.load("file.parquet")

  # TXT
  # df_txt = spark.read.text("file.txt")

  # CSV
  # df_csv = spark.read.csv("file.csv", header=True, inferSchema=True)

In [113]:
import os

os.listdir(dataset_path)

['recipes.parquet', 'reviews.parquet', 'reviews.csv', 'recipes.csv']

ใช้ดูว่าใน dataset folder มีไฟล์อะไรบ้าง

## 1. SparkSession

`SparkSession`
ใช้สำหรับอ่านข้อมูล, สร้าง DataFrame, ใช้ SQL และ save output

In [4]:
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .appName("FoodCom Spark Practice TH")
    .getOrCreate()
)

- `SparkSession.builder`  
  เริ่มสร้าง Spark application

- `.appName(...)`  
  ตั้งชื่อ application เพื่อดูใน log หรือ Spark UI

- `.getOrCreate()`  
  ถ้ามี SparkSession อยู่แล้วจะใช้ของเดิม ถ้ายังไม่มีจะสร้างใหม่

### (Scala) SparkSession

In [114]:
# Scala

'''
import org.apache.spark.sql.SparkSession

val spark = SparkSession.builder()
  .appName("FoodCom Spark Practice")
  .getOrCreate()
'''

'\nimport org.apache.spark.sql.SparkSession\n\nval spark = SparkSession.builder()\n  .appName("FoodCom Spark Practice")\n  .getOrCreate()\n'

## 2. อ่าน CSV แบบปกติ

เพื่อลด error จากการเดา schema ผิด ให้อ่าน CSV แบบ basic ก่อน โดยยังไม่ใช้ `inferSchema=True`

จากนั้นค่อย cast column ที่จำเป็นเอง

In [115]:
recipes_path = f"{dataset_path}/recipes.csv"
reviews_path = f"{dataset_path}/reviews.csv"

recipes_df = spark.read.csv(recipes_path, header=True, multiLine=True, escape='"')
reviews_df = spark.read.csv(reviews_path, header=True, multiLine=True, escape='"')

- `spark.read.csv(...)`  
  อ่านไฟล์ CSV เป็น Spark DataFrame

- `header=True`  
  ใช้แถวแรกเป็นชื่อ column

- ไม่ใช้ `inferSchema=True`  
  ทำให้ Spark อ่านข้อมูลเป็น string ก่อน วิธีนี้ basic และลดโอกาส error จากการเดาชนิดข้อมูลผิด

### (Scala) อ่าน CSV

In [116]:
# Scala note เท่านั้น

'''
val recipesDF = spark.read
  .option("header", "true")
  .csv("recipes.csv")
'''

'\nval recipesDF = spark.read\n  .option("header", "true")\n  .csv("recipes.csv")\n'

## 3. Inspect Data ดูข้อมูลเบื้องต้น

In [117]:
recipes_df.show()

+--------+--------------------+--------+--------------------+--------+--------+---------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+------------+--------------------+
|RecipeId|                Name|AuthorId|          AuthorName|CookTime|PrepTime|TotalTime|       DatePublished|         Description|              Images|   RecipeCategory|            Keywords|RecipeIngredientQuantities|RecipeIngredientParts|AggregatedRating|ReviewCount|Calories|FatContent|SaturatedFatContent|CholesterolContent|SodiumContent|CarbohydrateContent|FiberContent|SugarContent|ProteinContent|RecipeServings| RecipeYield|  RecipeInstructions|
+--------+--------------------+--------+--------------------+--------+--------+---------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+------------+--------------------+
|      38|Low-Fat Berry Blu...|    1533|              Dancer|   PT24H|   PT45M| PT24H45M|1999-08-09T21:46:00Z|Make and share th...|c("https://img.sn...|  Frozen Desserts|c("Dessert", "Low...|      c("4", "1/4", "1"...| c("blueberries", ...|             4.5|          4|   170.9|       2.5|                1.3|                 8|         29.8|               37.1|         3.6|        30.2|           3.2|             4|          NA|c("Toss 2 cups be...|
|      39|             Biryani|    1567|            elly9812|   PT25M|    PT4H|  PT4H25M|1999-08-29T13:12:00Z|Make and share th...|c("https://img.sn...|   Chicken Breast|c("Chicken Thigh ...|      c("1", "4", "2", ...| c("saffron", "mil...|               3|          1|  1110.7|      58.8|               16.6|             372.8|        368.4|               84.4|           9|        20.4|          63.4|             6|          NA|c("Soak saffron i...|
|      40|       Best Lemonade|    1566|      Stephen Little|    PT5M|   PT30M|    PT35M|1999-09-05T19:52:00Z|This is from one ...|c("https://img.sn...|        Beverages|c("Low Protein", ...|      c("1 1/2", "1", N...| c("sugar", "lemon...|             4.5|         10|   311.1|       0.2|                  0|                 0|          1.8|               81.5|         0.4|        77.2|           0.3|             4|          NA|c("Into a 1 quart...|
|      41|Carina's Tofu-Veg...|    1586|             Cyclopz|   PT20M|   PT24H| PT24H20M|1999-09-03T14:54:00Z|This dish is best...|c("https://img.sn...|         Soy/Tofu|c("Beans", "Veget...|      c("12", "1", "2",...| c("extra firm tof...|             4.5|          2|   536.1|        24|                3.8|                 0|       1558.6|               64.2|        17.3|        32.1|          29.3|             2|    4 kebabs|c("Drain the tofu...|
|      42|        Cabbage Soup|    1538|           Duckie067|   PT30M|   PT20M|    PT50M|1999-09-19T06:19:00Z|Make and share th...|"https://img.sndi...|        Vegetable|c("Low Protein", ...|      c("46", "4", "1",...| c("plain tomato j...|             4.5|         11|   103.6|       0.4|                0.1|                 0|        959.3|               25.1|         4.8|        17.7|           4.3|             4|          NA|c("Mix everything...|
|      43|Best Blackbottom Pie|   34879|Barefoot Beachcomber|    PT2H|   PT20M|  PT2H20M|1999-08-21T10:35:00Z|Make and share th...|        character(0)|              Pie|c("Dessert", "Wee...|      c("1 1/4", "1/4",...| c("graham cracker...|               1|          1|   437.9|      19.3|               10.9|              94.3|        267.6|                 58|         1.8|        42.5|             7|             8|1 9-inch pie|c("Graham Cracker...|
|      44|Warm Chicken A La...|    1596|       Joan Edington|    PT3M|   PT35M|    PT38M|1999-09-17T04:47:00Z|I copied this one...|"https://img.sndi...|          Chicken|c("Poultry", "Mea...|      c("12", "2", "3",...| c("chicken", "but...|               5|         23|   895.5|      66.8|               31.9|             405.8|        557.2|               29.1|         3.1|           5|          45.3|             2|          NA|c("Melt 1 1/2 ozs...|
|      45|Buttermilk Pie Wi...|    1580|           tristitia|   PT50M|   PT30M|  PT1H20M|1999-08-06T00:40:00Z|Make and share th...|"https://img.sndi...|              Pie|c("Dessert", "Hea...|      c("3/4", "1", "1"...| c("sugar", "marga...|               4|          3|     228|       7.1|                1.7|              24.5|        281.8|               37.5|         0.5|        24.7|           4.2|             8|          NA|c("Preheat oven t...|
|      46|A Jad - Cucumber ...|    1533|              Dancer|      NA|   PT25M|    PT25M|1999-08-11T19:48:00Z|Make and share th...|        character(0)|        Vegetable|c("Thai", "Asian"...|      c("1/2", "5", "2"...| c("rice vinegar",...|               5|          2|     4.3|         0|                  0|                 0|          0.7|                1.1|         0.2|         0.2|           0.1|            NA|       1 cup|c("Slice the cucu...|
|      47|Butter Pecan Cookies|    1573|              benluc|    PT9M|   PT55M|   PT1H4M|1999-09-07T09:01:00Z|Make and share th...|c("https://img.sn...|          Dessert|c("Cookie & Brown...|      c("3/4", "1/2", "...| c("butter", "brow...|               4|          2|      69|       5.6|                1.4|               6.3|           15|                4.5|         0.6|         1.6|           0.8|            NA|  84 cookies|c("Preheat oven t...|
|      48|    Boston Cream Pie|    1545|       Nancy Van Ess|      NA| PT2H15M|  PT2H15M|1999-08-24T04:35:00Z|Make and share th...|        character(0)|              Pie|c("Dessert", "Wee...|      c("1/2", "2 1/4",...| c("margarine", "c...|               2|          2|   688.2|      36.4|               12.9|             105.9|        722.3|                 84|         1.6|        46.2|           8.8|             8|       1 pie|c("Beat egg white...|
|      49|Chicken Breasts L...|  174711|    Queen Dragon Mom|   PT30M|   PT45M|  PT1H15M|1999-08-14T19:58:00Z|Make and share th...|c("https://img.sn...|   Chicken Breast|c("Chicken", "Pou...|      c("2", "2", "12",...| c("fresh mushroom...|               5|         21|   627.7|      24.9|                 13|               203|        848.9|               13.7|         0.6|           2|          57.9|             6|          NA|c("Cook mushrooms...|
|      50|   Biscotti Di Prato|    1752|            Bob Ross|   PT50M|   PT20M|  PT1H10M|1999-08-31T21:19:00Z|Make and share th...|"https://img.sndi...|          Dessert|c("Cookie & Brown...|      c("3 3/4", "2", "...| c("flour", "sugar...|             4.5|          2|    89.4|       2.6|                0.3|              16.6|         23.5|               14.5|         0.8|         7.3|           2.3|            NA| 56 biscotti|c("EGG WASH 1 Egg...|
|      51|            Chai Tea|    1550|       Linda Sundbye|   PT25M|   PT15M|    PT40M|1999-08-16T05:10:00Z|Make and share th...|        character(0)|        Beverages|c("Free Of...", "...|      c("4", "1", "1", ...| c("water", "black...|               3|          1|    69.2|       3.8|                2.1|              12.8|         53.2|                  6|         0.7|           0|           3.5|             4|          NA|c("Bring water an...|
|      52|     Cafe Cappuccino|    2178|               troyh|      NA|    PT5M|     PT5M|1999-08-31T21:05:00Z|Make and share th...|c("https://img.sn...|        Beverages|c("Low Cholestero...|      c("1/2", "3/4", "...| c("instant coffee...|               5|          1|    62.2|       0.1|                  0|               1.3|         36.6|               12.8|           0|        11.8|           2.7|            18|  2 1/4 cups|c("Stir ingredien...|
|      53|Jimmy G's Carrot ...|    1772|            Jimg2040|   PT45M|  PT1H5M|  PT1H50M|1999-09-08T15:39:00Z|Make and share th...|        character(0)|          Dessert|c("Pineapple", "T...|      c("2", "2", "1", ...| c("all-purpose fl...|               3|          1|   372.9|      10.6|                3.2|                62|          190|               66.2|         3.4|        40.9|           6.6|            NA|          NA|c("Grease and lig...|
|      54|         Carrot Cake|    1535|  Marg CaymanDesigns|   PT50M|   PT45M|  PT1H35M|1999-09-13T15:20:00Z|This is one of th...|c("https://img.sn...|          Dessert|c("Vegetable", "W...|      c("3", "4", "1 1/...| c("carrots", "egg...|               5|         17|   522.6|      27.1|                4.9|              69.8|        534.8|                 67|         1.6|        47.9|             5|            12|     1 bundt|c("Beat together ...|
|      55|Betty Crocker's S...|    1538|           Duckie067|    PT2H|    PT5M|   PT2H5M|1999-09-15T03:25:00Z|Make and share th...|c("https://img.sn...|Southwestern U.S.|c("Mexican", "Low...|      c("5", "1", "1/2"...| c("avocados", "to...|               5|          4|   415.9|      36.9|                5.4|                 0|        310.6|               24.9|        17.3|         2.8|           5.5|             4|          NA|c("Peel and mash ...|
|      56|      Buttermilk Pie|    1581|            thefensk|    PT1H|   PT20M|  PT1H20M|1999-08-30T10:02:00Z|This recipe was o...|c("https://img.sn...|              Pie|c("Dessert", "Ove...|      c("1/2", "1 1/2",...| c("butter", "marg...|               5|        171|   395.9|      19.1|                9.8|             101.5|        269.8|               52.2|         0.7|        39.9|             5|             8|          NA|c("Preheat oven t...|
|      57|    Black Bean Salsa|    1569|              Linda7|      NA|   PT10M|    PT10M|1999-08-31T21:02:00Z|Make and share th...|        character(0)|           Sauces|c("Black Beans", ...|      c("2", "2 -3", "2...| c("black beans", ...|               3|          1|   114.3|       3.8|                0.5|                 0|          3.7|               15.6|         5.5|         1.4|           5.4|             8|          NA|c("Combine all in...|
+--------+--------------------+--------+--------------------+--------+--------+---------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+------------+--------------------+
only showing top 20 rows

In [118]:

recipes_df.show(5)

+--------+--------------------+--------+--------------+--------+--------+---------+--------------------+--------------------+--------------------+---------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+-----------+--------------------+
|RecipeId|                Name|AuthorId|    AuthorName|CookTime|PrepTime|TotalTime|       DatePublished|         Description|              Images| RecipeCategory|            Keywords|RecipeIngredientQuantities|RecipeIngredientParts|AggregatedRating|ReviewCount|Calories|FatContent|SaturatedFatContent|CholesterolContent|SodiumContent|CarbohydrateContent|FiberContent|SugarContent|ProteinContent|RecipeServings|RecipeYield|  RecipeInstructions|
+--------+--------------------+--------+--------------+--------+--------+---------+--------------------+--------------------+--------------------+---------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+-----------+--------------------+
|      38|Low-Fat Berry Blu...|    1533|        Dancer|   PT24H|   PT45M| PT24H45M|1999-08-09T21:46:00Z|Make and share th...|c("https://img.sn...|Frozen Desserts|c("Dessert", "Low...|      c("4", "1/4", "1"...| c("blueberries", ...|             4.5|          4|   170.9|       2.5|                1.3|                 8|         29.8|               37.1|         3.6|        30.2|           3.2|             4|         NA|c("Toss 2 cups be...|
|      39|             Biryani|    1567|      elly9812|   PT25M|    PT4H|  PT4H25M|1999-08-29T13:12:00Z|Make and share th...|c("https://img.sn...| Chicken Breast|c("Chicken Thigh ...|      c("1", "4", "2", ...| c("saffron", "mil...|               3|          1|  1110.7|      58.8|               16.6|             372.8|        368.4|               84.4|           9|        20.4|          63.4|             6|         NA|c("Soak saffron i...|
|      40|       Best Lemonade|    1566|Stephen Little|    PT5M|   PT30M|    PT35M|1999-09-05T19:52:00Z|This is from one ...|c("https://img.sn...|      Beverages|c("Low Protein", ...|      c("1 1/2", "1", N...| c("sugar", "lemon...|             4.5|         10|   311.1|       0.2|                  0|                 0|          1.8|               81.5|         0.4|        77.2|           0.3|             4|         NA|c("Into a 1 quart...|
|      41|Carina's Tofu-Veg...|    1586|       Cyclopz|   PT20M|   PT24H| PT24H20M|1999-09-03T14:54:00Z|This dish is best...|c("https://img.sn...|       Soy/Tofu|c("Beans", "Veget...|      c("12", "1", "2",...| c("extra firm tof...|             4.5|          2|   536.1|        24|                3.8|                 0|       1558.6|               64.2|        17.3|        32.1|          29.3|             2|   4 kebabs|c("Drain the tofu...|
|      42|        Cabbage Soup|    1538|     Duckie067|   PT30M|   PT20M|    PT50M|1999-09-19T06:19:00Z|Make and share th...|"https://img.sndi...|      Vegetable|c("Low Protein", ...|      c("46", "4", "1",...| c("plain tomato j...|             4.5|         11|   103.6|       0.4|                0.1|                 0|        959.3|               25.1|         4.8|        17.7|           4.3|             4|         NA|c("Mix everything...|
+--------+--------------------+--------+--------------+--------+--------+---------+--------------------+--------------------+--------------------+---------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+-----------+--------------------+
only showing top 5 rows

- `show(5)`  
  แสดงข้อมูล 5 แถวแรกในรูปแบบตาราง

- `show()` เป็น Action  
  แปลว่า Spark จะเริ่มอ่านข้อมูลจริงตอนเจอคำสั่งนี้

In [119]:
recipes_df.printSchema()

root
 |-- RecipeId: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- AuthorId: string (nullable = true)
 |-- AuthorName: string (nullable = true)
 |-- CookTime: string (nullable = true)
 |-- PrepTime: string (nullable = true)
 |-- TotalTime: string (nullable = true)
 |-- DatePublished: string (nullable = true)
 |-- Description: string (nullable = true)
 |-- Images: string (nullable = true)
 |-- RecipeCategory: string (nullable = true)
 |-- Keywords: string (nullable = true)
 |-- RecipeIngredientQuantities: string (nullable = true)
 |-- RecipeIngredientParts: string (nullable = true)
 |-- AggregatedRating: string (nullable = true)
 |-- ReviewCount: string (nullable = true)
 |-- Calories: string (nullable = true)
 |-- FatContent: string (nullable = true)
 |-- SaturatedFatContent: string (nullable = true)
 |-- CholesterolContent: string (nullable = true)
 |-- SodiumContent: string (nullable = true)
 |-- CarbohydrateContent: string (nullable = true)
 |-- FiberContent: string (nullable = true)
 |-- SugarContent: string (nullable = true)
 |-- ProteinContent: string (nullable = true)
 |-- RecipeServings: string (nullable = true)
 |-- RecipeYield: string (nullable = true)
 |-- RecipeInstructions: string (nullable = true)

- `printSchema()`  
  แสดงโครงสร้างของ DataFrame เช่น ชื่อ column และ data type

In [120]:
recipes_df.dtypes

[('RecipeId', 'string'),
 ('Name', 'string'),
 ('AuthorId', 'string'),
 ('AuthorName', 'string'),
 ('CookTime', 'string'),
 ('PrepTime', 'string'),
 ('TotalTime', 'string'),
 ('DatePublished', 'string'),
 ('Description', 'string'),
 ('Images', 'string'),
 ('RecipeCategory', 'string'),
 ('Keywords', 'string'),
 ('RecipeIngredientQuantities', 'string'),
 ('RecipeIngredientParts', 'string'),
 ('AggregatedRating', 'string'),
 ('ReviewCount', 'string'),
 ('Calories', 'string'),
 ('FatContent', 'string'),
 ('SaturatedFatContent', 'string'),
 ('CholesterolContent', 'string'),
 ('SodiumContent', 'string'),
 ('CarbohydrateContent', 'string'),
 ('FiberContent', 'string'),
 ('SugarContent', 'string'),
 ('ProteinContent', 'string'),
 ('RecipeServings', 'string'),
 ('RecipeYield', 'string'),
 ('RecipeInstructions', 'string')]



- `dtypes`  
  แสดงชื่อ column พร้อม data type เป็น list

ใช้เช็กเร็ว ๆ ว่าแต่ละ column ถูกอ่านเป็นชนิดอะไร

In [121]:
recipes_df.columns

['RecipeId',
 'Name',
 'AuthorId',
 'AuthorName',
 'CookTime',
 'PrepTime',
 'TotalTime',
 'DatePublished',
 'Description',
 'Images',
 'RecipeCategory',
 'Keywords',
 'RecipeIngredientQuantities',
 'RecipeIngredientParts',
 'AggregatedRating',
 'ReviewCount',
 'Calories',
 'FatContent',
 'SaturatedFatContent',
 'CholesterolContent',
 'SodiumContent',
 'CarbohydrateContent',
 'FiberContent',
 'SugarContent',
 'ProteinContent',
 'RecipeServings',
 'RecipeYield',
 'RecipeInstructions']

- `columns`  
  แสดงชื่อ column ทั้งหมดใน DataFrame เป็น list

In [62]:
recipes_df.count()

522517

522517

- `count()` นับจำนวน row ทั้งหมด ถ้าข้อมูลใหญ่มากอาจใช้เวลานาน

In [63]:
reviews_df.show(5)
reviews_df.printSchema()
reviews_df.count()

+--------+--------+--------+----------------+------+--------------------+--------------------+--------------------+
|ReviewId|RecipeId|AuthorId|      AuthorName|Rating|              Review|       DateSubmitted|        DateModified|
+--------+--------+--------+----------------+------+--------------------+--------------------+--------------------+
|       2|     992|    2008|       gayg msft|     5|better than any y...|2000-01-25T21:44:00Z|2000-01-25T21:44:00Z|
|       7|    4384|    1634|   Bill Hilbrich|     4|I cut back on the...|2001-10-17T16:49:59Z|2001-10-17T16:49:59Z|
|       9|    4523|    2046|Gay Gilmore ckpt|     2|i think i did som...|2000-02-25T09:00:00Z|2000-02-25T09:00:00Z|
|      13|    7435|    1773|   Malarkey Test|     5|easily the best i...|2000-03-13T21:15:00Z|2000-03-13T21:15:00Z|
|      14|      44|    2085|      Tony Small|     5|  An excellent dish.|2000-03-28T12:51:00Z|2000-03-28T12:51:00Z|
+--------+--------+--------+----------------+------+--------------------+--------------------+--------------------+
only showing top 5 rows
root
 |-- ReviewId: string (nullable = true)
 |-- RecipeId: string (nullable = true)
 |-- AuthorId: string (nullable = true)
 |-- AuthorName: string (nullable = true)
 |-- Rating: string (nullable = true)
 |-- Review: string (nullable = true)
 |-- DateSubmitted: string (nullable = true)
 |-- DateModified: string (nullable = true)

1401982

+--------+--------+--------+----------------+------+--------------------+--------------------+--------------------+
|ReviewId|RecipeId|AuthorId|      AuthorName|Rating|              Review|       DateSubmitted|        DateModified|
+--------+--------+--------+----------------+------+--------------------+--------------------+--------------------+
|       2|     992|    2008|       gayg msft|     5|better than any y...|2000-01-25T21:44:00Z|2000-01-25T21:44:00Z|
|       7|    4384|    1634|   Bill Hilbrich|     4|I cut back on the...|2001-10-17T16:49:59Z|2001-10-17T16:49:59Z|
|       9|    4523|    2046|Gay Gilmore ckpt|     2|i think i did som...|2000-02-25T09:00:00Z|2000-02-25T09:00:00Z|
|      13|    7435|    1773|   Malarkey Test|     5|easily the best i...|2000-03-13T21:15:00Z|2000-03-13T21:15:00Z|
|      14|      44|    2085|      Tony Small|     5|  An excellent dish.|2000-03-28T12:51:00Z|2000-03-28T12:51:00Z|
+--------+--------+--------+----------------+------+--------------------+--------------------+--------------------+
only showing top 5 rows
root
 |-- ReviewId: string (nullable = true)
 |-- RecipeId: string (nullable = true)
 |-- AuthorId: string (nullable = true)
 |-- AuthorName: string (nullable = true)
 |-- Rating: string (nullable = true)
 |-- Review: string (nullable = true)
 |-- DateSubmitted: string (nullable = true)
 |-- DateModified: string (nullable = true)

1401982

## 4. ดูข้อมูลหลายแบบ: show, head, first, take

In [64]:
recipes_df.show(3)

+--------+--------------------+--------+--------------+--------+--------+---------+--------------------+--------------------+--------------------+---------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+-----------+--------------------+
|RecipeId|                Name|AuthorId|    AuthorName|CookTime|PrepTime|TotalTime|       DatePublished|         Description|              Images| RecipeCategory|            Keywords|RecipeIngredientQuantities|RecipeIngredientParts|AggregatedRating|ReviewCount|Calories|FatContent|SaturatedFatContent|CholesterolContent|SodiumContent|CarbohydrateContent|FiberContent|SugarContent|ProteinContent|RecipeServings|RecipeYield|  RecipeInstructions|
+--------+--------------------+--------+--------------+--------+--------+---------+--------------------+--------------------+--------------------+---------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+-----------+--------------------+
|      38|Low-Fat Berry Blu...|    1533|        Dancer|   PT24H|   PT45M| PT24H45M|1999-08-09T21:46:00Z|Make and share th...|c("https://img.sn...|Frozen Desserts|c("Dessert", "Low...|      c("4", "1/4", "1"...| c("blueberries", ...|             4.5|          4|   170.9|       2.5|                1.3|                 8|         29.8|               37.1|         3.6|        30.2|           3.2|             4|         NA|c("Toss 2 cups be...|
|      39|             Biryani|    1567|      elly9812|   PT25M|    PT4H|  PT4H25M|1999-08-29T13:12:00Z|Make and share th...|c("https://img.sn...| Chicken Breast|c("Chicken Thigh ...|      c("1", "4", "2", ...| c("saffron", "mil...|               3|          1|  1110.7|      58.8|               16.6|             372.8|        368.4|               84.4|           9|        20.4|          63.4|             6|         NA|c("Soak saffron i...|
|      40|       Best Lemonade|    1566|Stephen Little|    PT5M|   PT30M|    PT35M|1999-09-05T19:52:00Z|This is from one ...|c("https://img.sn...|      Beverages|c("Low Protein", ...|      c("1 1/2", "1", N...| c("sugar", "lemon...|             4.5|         10|   311.1|       0.2|                  0|                 0|          1.8|               81.5|         0.4|        77.2|           0.3|             4|         NA|c("Into a 1 quart...|
+--------+--------------------+--------+--------------+--------+--------+---------+--------------------+--------------------+--------------------+---------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+-----------+--------------------+
only showing top 3 rows
+--------+--------------------+--------+--------------+--------+--------+---------+--------------------+--------------------+--------------------+---------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+-----------+--------------------+
|RecipeId|                Name|AuthorId|    AuthorName|CookTime|PrepTime|TotalTime|       DatePublished|         Description|              Images| RecipeCategory|            Keywords|RecipeIngredientQuantities|RecipeIngredientParts|AggregatedRating|ReviewCount|Calories|FatContent|SaturatedFatContent|CholesterolContent|SodiumContent|CarbohydrateContent|FiberContent|SugarContent|ProteinContent|RecipeServings|RecipeYield|  RecipeInstructions|
+--------+--------------------+--------+--------------+--------+--------+---------+--------------------+--------------------+--------------------+---------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+-----------+--------------------+
|      38|Low-Fat Berry Blu...|    1533|        Dancer|   PT24H|   PT45M| PT24H45M|1999-08-09T21:46:00Z|Make and share th...|c("https://img.sn...|Frozen Desserts|c("Dessert", "Low...|      c("4", "1/4", "1"...| c("blueberries", ...|             4.5|          4|   170.9|       2.5|                1.3|                 8|         29.8|               37.1|         3.6|        30.2|           3.2|             4|         NA|c("Toss 2 cups be...|
|      39|             Biryani|    1567|      elly9812|   PT25M|    PT4H|  PT4H25M|1999-08-29T13:12:00Z|Make and share th...|c("https://img.sn...| Chicken Breast|c("Chicken Thigh ...|      c("1", "4", "2", ...| c("saffron", "mil...|               3|          1|  1110.7|      58.8|               16.6|             372.8|        368.4|               84.4|           9|        20.4|          63.4|             6|         NA|c("Soak saffron i...|
|      40|       Best Lemonade|    1566|Stephen Little|    PT5M|   PT30M|    PT35M|1999-09-05T19:52:00Z|This is from one ...|c("https://img.sn...|      Beverages|c("Low Protein", ...|      c("1 1/2", "1", N...| c("sugar", "lemon...|             4.5|         10|   311.1|       0.2|                  0|                 0|          1.8|               81.5|         0.4|        77.2|           0.3|             4|         NA|c("Into a 1 quart...|
+--------+--------------------+--------+--------------+--------+--------+---------+--------------------+--------------------+--------------------+---------------+--------------------+--------------------------+---------------------+----------------+-----------+--------+----------+-------------------+------------------+-------------+-------------------+------------+------------+--------------+--------------+-----------+--------------------+
only showing top 3 rows

- `show(3)`  แสดง 3 แถวแรกเป็นตาราง

In [65]:
recipes_df.head(3)

[Row(RecipeId='38', Name='Low-Fat Berry Blue Frozen Dessert', AuthorId='1533', AuthorName='Dancer', CookTime='PT24H', PrepTime='PT45M', TotalTime='PT24H45M', DatePublished='1999-08-09T21:46:00Z', Description='Make and share this Low-Fat Berry Blue Frozen Dessert recipe from Food.com.', Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/YUeirxMLQaeE1h3v3qnM_229%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/AFPDDHATWzQ0b1CDpDAT_255%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/UYgf9nwMT2SGGJCuzILO_228%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/PeBMJN2TGSaYks2759BA_20140722_202142.jpg", \n"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/picuaETeN.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/pictzvxW5.jpg")', RecipeCategory='Frozen Desserts', Keywords='c("Dessert", "Low Protein", "Low Cholesterol", "Healthy", "Free Of...", "Summer", "Weeknight", "Freezer", "Easy")', RecipeIngredientQuantities='c("4", "1/4", "1", "1")', RecipeIngredientParts='c("blueberries", "granulated sugar", "vanilla yogurt", "lemon juice")', AggregatedRating='4.5', ReviewCount='4', Calories='170.9', FatContent='2.5', SaturatedFatContent='1.3', CholesterolContent='8', SodiumContent='29.8', CarbohydrateContent='37.1', FiberContent='3.6', SugarContent='30.2', ProteinContent='3.2', RecipeServings='4', RecipeYield='NA', RecipeInstructions='c("Toss 2 cups berries with sugar.", "Let stand for 45 minutes, stirring occasionally.", "Transfer berry-sugar mixture to food processor.", "Add yogurt and process until smooth.", "Strain through fine sieve. Pour into baking pan (or transfer to ice cream maker and process according to manufacturers\' directions). Freeze uncovered until edges are solid but centre is soft.  Transfer to processor and blend until smooth again.", "Return to pan and freeze until edges are solid.", "Transfer to processor and blend until smooth again.", \n"Fold in remaining 2 cups of blueberries.", "Pour into plastic mold and freeze overnight. Let soften slightly to serve.")'),
 Row(RecipeId='39', Name='Biryani', AuthorId='1567', AuthorName='elly9812', CookTime='PT25M', PrepTime='PT4H', TotalTime='PT4H25M', DatePublished='1999-08-29T13:12:00Z', Description='Make and share this Biryani recipe from Food.com.', Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/39/picM9Mhnw.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/39/picHv4Ocr.jpg")', RecipeCategory='Chicken Breast', Keywords='c("Chicken Thigh & Leg", "Chicken", "Poultry", "Meat", "Asian", "Indian", "Weeknight", "Stove Top")', RecipeIngredientQuantities='c("1", "4", "2", "2", "8", "1/4", "8", "1/2", "1", "1", "1/4", "1/4", "1/2", "1/4", "2", "3", NA, "2", "1", "1", "8", "2", "1/3", "1/3", "1/3", "6")', RecipeIngredientParts='c("saffron", "milk", "hot green chili peppers", "onions", "garlic", "clove", "peppercorns", "cardamom seed", "cumin seed", "poppy seed", "mace", "cilantro", "mint leaf", "fresh lemon juice", "plain yogurt", "boneless chicken", "salt", "ghee", "onion", "tomatoes", "basmati rice", "long-grain rice", "raisins", "cashews", "eggs")', AggregatedRating='3', ReviewCount='1', Calories='1110.7', FatContent='58.8', SaturatedFatContent='16.6', CholesterolContent='372.8', SodiumContent='368.4', CarbohydrateContent='84.4', FiberContent='9', SugarContent='20.4', ProteinContent='63.4', RecipeServings='6', RecipeYield='NA', RecipeInstructions='c("Soak saffron in warm milk for 5 minutes and puree in blender.", "Add chiles, onions, ginger, garlic, cloves, peppercorns, cardamom seeds, cinnamon, coriander and cumin seeds, poppy seeds, nutmeg, mace, cilantro or mint leaves and lemon juice. Blend into smooth paste. Put paste into large bowl, add yogurt and mix well.", "Marinate chicken in yogurt mixture with salt, covered for at least 2 - 6 hours in refrigerator.", "In skillet. heat oil over medium heat for 1 minute. Add ghee and 15 seconds later add onion and fry for about8 minutes.", \n"Reserve for garnish.", "In same skillet, cook chicken with its marinade with tomatoes for about 10 minutes over medium heat, uncovered.", "Remove chicken pieces from the sauce and set aside. Add rice to sauce, bring to boil, and cook, covered over low heat for 15 minutes.", "Return chicken and add raisins, cashews and almonds; mix well.", "Simmer, covered for 5 minutes.", "Place chicken, eggs and rice in large serving dish in such a way that yellow of the eggs, the saffron-colored rice, the nuts and the chicken make a colorful display.", \n"Add reserved onion as garnish.")'),
 Row(RecipeId='40', Name='Best Lemonade', AuthorId='1566', AuthorName='Stephen Little', CookTime='PT5M', PrepTime='PT30M', TotalTime='PT35M', DatePublished='1999-09-05T19:52:00Z', Description="This is from one of my  first Good House Keeping cookbooks.  You must use a *zester* in order to avoid getting any of that bitter rind, and when you zest the lemons, zest them onto some sugar from the recipe (the sugar will 'catch' all of the oils).  I also advise you from personal experience to use only the best skinned lemons for the best flavor.", Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/40/picJ4Sz3N.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/40/pic23FWio.jpg")', RecipeCategory='Beverages', Keywords='c("Low Protein", "Low Cholesterol", "Healthy", "Summer", "< 60 Mins")', RecipeIngredientQuantities='c("1 1/2", "1", NA, "1 1/2", NA, "3/4")', RecipeIngredientParts='c("sugar", "lemons, rind of", "lemon, zest of", "fresh water", "fresh lemon juice")', AggregatedRating='4.5', ReviewCount='10', Calories='311.1', FatContent='0.2', SaturatedFatContent='0', CholesterolContent='0', SodiumContent='1.8', CarbohydrateContent='81.5', FiberContent='0.4', SugarContent='77.2', ProteinContent='0.3', RecipeServings='4', RecipeYield='NA', RecipeInstructions='c("Into a 1 quart Jar with tight fitting lid, put sugar and lemon peel, or zest;  add 1 1/2 cups very hot water (not from tap!). With lid fitted firmly, shake jar until sugar is dissolved.", "Add lemon juice. Refrigerate until chilled.", "To Serve: Into each 12-ounce glass, over ice cubes, pour 1/4 cup of the lemon syrup.", "Then add chilled club soda or, if you prefer, water.", "Stir to mix well.")')]

[Row(RecipeId='38', Name='Low-Fat Berry Blue Frozen Dessert', AuthorId='1533', AuthorName='Dancer', CookTime='PT24H', PrepTime='PT45M', TotalTime='PT24H45M', DatePublished='1999-08-09T21:46:00Z', Description='Make and share this Low-Fat Berry Blue Frozen Dessert recipe from Food.com.', Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/YUeirxMLQaeE1h3v3qnM_229%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/AFPDDHATWzQ0b1CDpDAT_255%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/UYgf9nwMT2SGGJCuzILO_228%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/PeBMJN2TGSaYks2759BA_20140722_202142.jpg", \n"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/picuaETeN.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/pictzvxW5.jpg")', RecipeCategory='Frozen Desserts', Keywords='c("Dessert", "Low Protein", "Low Cholesterol", "Healthy", "Free Of...", "Summer", "Weeknight", "Freezer", "Easy")', RecipeIngredientQuantities='c("4", "1/4", "1", "1")', RecipeIngredientParts='c("blueberries", "granulated sugar", "vanilla yogurt", "lemon juice")', AggregatedRating='4.5', ReviewCount='4', Calories='170.9', FatContent='2.5', SaturatedFatContent='1.3', CholesterolContent='8', SodiumContent='29.8', CarbohydrateContent='37.1', FiberContent='3.6', SugarContent='30.2', ProteinContent='3.2', RecipeServings='4', RecipeYield='NA', RecipeInstructions='c("Toss 2 cups berries with sugar.", "Let stand for 45 minutes, stirring occasionally.", "Transfer berry-sugar mixture to food processor.", "Add yogurt and process until smooth.", "Strain through fine sieve. Pour into baking pan (or transfer to ice cream maker and process according to manufacturers\' directions). Freeze uncovered until edges are solid but centre is soft.  Transfer to processor and blend until smooth again.", "Return to pan and freeze until edges are solid.", "Transfer to processor and blend until smooth again.", \n"Fold in remaining 2 cups of blueberries.", "Pour into plastic mold and freeze overnight. Let soften slightly to serve.")'),
 Row(RecipeId='39', Name='Biryani', AuthorId='1567', AuthorName='elly9812', CookTime='PT25M', PrepTime='PT4H', TotalTime='PT4H25M', DatePublished='1999-08-29T13:12:00Z', Description='Make and share this Biryani recipe from Food.com.', Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/39/picM9Mhnw.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/39/picHv4Ocr.jpg")', RecipeCategory='Chicken Breast', Keywords='c("Chicken Thigh & Leg", "Chicken", "Poultry", "Meat", "Asian", "Indian", "Weeknight", "Stove Top")', RecipeIngredientQuantities='c("1", "4", "2", "2", "8", "1/4", "8", "1/2", "1", "1", "1/4", "1/4", "1/2", "1/4", "2", "3", NA, "2", "1", "1", "8", "2", "1/3", "1/3", "1/3", "6")', RecipeIngredientParts='c("saffron", "milk", "hot green chili peppers", "onions", "garlic", "clove", "peppercorns", "cardamom seed", "cumin seed", "poppy seed", "mace", "cilantro", "mint leaf", "fresh lemon juice", "plain yogurt", "boneless chicken", "salt", "ghee", "onion", "tomatoes", "basmati rice", "long-grain rice", "raisins", "cashews", "eggs")', AggregatedRating='3', ReviewCount='1', Calories='1110.7', FatContent='58.8', SaturatedFatContent='16.6', CholesterolContent='372.8', SodiumContent='368.4', CarbohydrateContent='84.4', FiberContent='9', SugarContent='20.4', ProteinContent='63.4', RecipeServings='6', RecipeYield='NA', RecipeInstructions='c("Soak saffron in warm milk for 5 minutes and puree in blender.", "Add chiles, onions, ginger, garlic, cloves, peppercorns, cardamom seeds, cinnamon, coriander and cumin seeds, poppy seeds, nutmeg, mace, cilantro or mint leaves and lemon juice. Blend into smooth paste. Put paste into large bowl, add yogurt and mix well.", "Marinate chicken in yogurt mixture with salt, covered for at least 2 - 6 hours in refrigerator.", "In skillet. heat oil over medium heat for 1 minute. Add ghee and 15 seconds later add onion and fry for about8 minutes.", \n"Reserve for garnish.", "In same skillet, cook chicken with its marinade with tomatoes for about 10 minutes over medium heat, uncovered.", "Remove chicken pieces from the sauce and set aside. Add rice to sauce, bring to boil, and cook, covered over low heat for 15 minutes.", "Return chicken and add raisins, cashews and almonds; mix well.", "Simmer, covered for 5 minutes.", "Place chicken, eggs and rice in large serving dish in such a way that yellow of the eggs, the saffron-colored rice, the nuts and the chicken make a colorful display.", \n"Add reserved onion as garnish.")'),
 Row(RecipeId='40', Name='Best Lemonade', AuthorId='1566', AuthorName='Stephen Little', CookTime='PT5M', PrepTime='PT30M', TotalTime='PT35M', DatePublished='1999-09-05T19:52:00Z', Description="This is from one of my  first Good House Keeping cookbooks.  You must use a *zester* in order to avoid getting any of that bitter rind, and when you zest the lemons, zest them onto some sugar from the recipe (the sugar will 'catch' all of the oils).  I also advise you from personal experience to use only the best skinned lemons for the best flavor.", Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/40/picJ4Sz3N.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/40/pic23FWio.jpg")', RecipeCategory='Beverages', Keywords='c("Low Protein", "Low Cholesterol", "Healthy", "Summer", "< 60 Mins")', RecipeIngredientQuantities='c("1 1/2", "1", NA, "1 1/2", NA, "3/4")', RecipeIngredientParts='c("sugar", "lemons, rind of", "lemon, zest of", "fresh water", "fresh lemon juice")', AggregatedRating='4.5', ReviewCount='10', Calories='311.1', FatContent='0.2', SaturatedFatContent='0', CholesterolContent='0', SodiumContent='1.8', CarbohydrateContent='81.5', FiberContent='0.4', SugarContent='77.2', ProteinContent='0.3', RecipeServings='4', RecipeYield='NA', RecipeInstructions='c("Into a 1 quart Jar with tight fitting lid, put sugar and lemon peel, or zest;  add 1 1/2 cups very hot water (not from tap!). With lid fitted firmly, shake jar until sugar is dissolved.", "Add lemon juice. Refrigerate until chilled.", "To Serve: Into each 12-ounce glass, over ice cubes, pour 1/4 cup of the lemon syrup.", "Then add chilled club soda or, if you prefer, water.", "Stir to mix well.")')]

- `head(3)`  ดึง 3 แถวแรกออกมาเป็น list ของ Row

ใช้กับข้อมูลจำนวนน้อยเท่านั้น เพราะข้อมูลถูกดึงกลับมาที่ driver

In [66]:
recipes_df.first()

Row(RecipeId='38', Name='Low-Fat Berry Blue Frozen Dessert', AuthorId='1533', AuthorName='Dancer', CookTime='PT24H', PrepTime='PT45M', TotalTime='PT24H45M', DatePublished='1999-08-09T21:46:00Z', Description='Make and share this Low-Fat Berry Blue Frozen Dessert recipe from Food.com.', Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/YUeirxMLQaeE1h3v3qnM_229%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/AFPDDHATWzQ0b1CDpDAT_255%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/UYgf9nwMT2SGGJCuzILO_228%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/PeBMJN2TGSaYks2759BA_20140722_202142.jpg", \n"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/picuaETeN.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/pictzvxW5.jpg")', RecipeCategory='Frozen Desserts', Keywords='c("Dessert", "Low Protein", "Low Cholesterol", "Healthy", "Free Of...", "Summer", "Weeknight", "Freezer", "Easy")', RecipeIngredientQuantities='c("4", "1/4", "1", "1")', RecipeIngredientParts='c("blueberries", "granulated sugar", "vanilla yogurt", "lemon juice")', AggregatedRating='4.5', ReviewCount='4', Calories='170.9', FatContent='2.5', SaturatedFatContent='1.3', CholesterolContent='8', SodiumContent='29.8', CarbohydrateContent='37.1', FiberContent='3.6', SugarContent='30.2', ProteinContent='3.2', RecipeServings='4', RecipeYield='NA', RecipeInstructions='c("Toss 2 cups berries with sugar.", "Let stand for 45 minutes, stirring occasionally.", "Transfer berry-sugar mixture to food processor.", "Add yogurt and process until smooth.", "Strain through fine sieve. Pour into baking pan (or transfer to ice cream maker and process according to manufacturers\' directions). Freeze uncovered until edges are solid but centre is soft.  Transfer to processor and blend until smooth again.", "Return to pan and freeze until edges are solid.", "Transfer to processor and blend until smooth again.", \n"Fold in remaining 2 cups of blueberries.", "Pour into plastic mold and freeze overnight. Let soften slightly to serve.")')

Row(RecipeId='38', Name='Low-Fat Berry Blue Frozen Dessert', AuthorId='1533', AuthorName='Dancer', CookTime='PT24H', PrepTime='PT45M', TotalTime='PT24H45M', DatePublished='1999-08-09T21:46:00Z', Description='Make and share this Low-Fat Berry Blue Frozen Dessert recipe from Food.com.', Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/YUeirxMLQaeE1h3v3qnM_229%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/AFPDDHATWzQ0b1CDpDAT_255%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/UYgf9nwMT2SGGJCuzILO_228%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/PeBMJN2TGSaYks2759BA_20140722_202142.jpg", \n"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/picuaETeN.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/pictzvxW5.jpg")', RecipeCategory='Frozen Desserts', Keywords='c("Dessert", "Low Protein", "Low Cholesterol", "Healthy", "Free Of...", "Summer", "Weeknight", "Freezer", "Easy")', RecipeIngredientQuantities='c("4", "1/4", "1", "1")', RecipeIngredientParts='c("blueberries", "granulated sugar", "vanilla yogurt", "lemon juice")', AggregatedRating='4.5', ReviewCount='4', Calories='170.9', FatContent='2.5', SaturatedFatContent='1.3', CholesterolContent='8', SodiumContent='29.8', CarbohydrateContent='37.1', FiberContent='3.6', SugarContent='30.2', ProteinContent='3.2', RecipeServings='4', RecipeYield='NA', RecipeInstructions='c("Toss 2 cups berries with sugar.", "Let stand for 45 minutes, stirring occasionally.", "Transfer berry-sugar mixture to food processor.", "Add yogurt and process until smooth.", "Strain through fine sieve. Pour into baking pan (or transfer to ice cream maker and process according to manufacturers\' directions). Freeze uncovered until edges are solid but centre is soft.  Transfer to processor and blend until smooth again.", "Return to pan and freeze until edges are solid.", "Transfer to processor and blend until smooth again.", \n"Fold in remaining 2 cups of blueberries.", "Pour into plastic mold and freeze overnight. Let soften slightly to serve.")')

- `first()`  
  ดึงแถวแรกของ DataFrame

In [67]:
recipes_df.take(2)

[Row(RecipeId='38', Name='Low-Fat Berry Blue Frozen Dessert', AuthorId='1533', AuthorName='Dancer', CookTime='PT24H', PrepTime='PT45M', TotalTime='PT24H45M', DatePublished='1999-08-09T21:46:00Z', Description='Make and share this Low-Fat Berry Blue Frozen Dessert recipe from Food.com.', Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/YUeirxMLQaeE1h3v3qnM_229%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/AFPDDHATWzQ0b1CDpDAT_255%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/UYgf9nwMT2SGGJCuzILO_228%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/PeBMJN2TGSaYks2759BA_20140722_202142.jpg", \n"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/picuaETeN.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/pictzvxW5.jpg")', RecipeCategory='Frozen Desserts', Keywords='c("Dessert", "Low Protein", "Low Cholesterol", "Healthy", "Free Of...", "Summer", "Weeknight", "Freezer", "Easy")', RecipeIngredientQuantities='c("4", "1/4", "1", "1")', RecipeIngredientParts='c("blueberries", "granulated sugar", "vanilla yogurt", "lemon juice")', AggregatedRating='4.5', ReviewCount='4', Calories='170.9', FatContent='2.5', SaturatedFatContent='1.3', CholesterolContent='8', SodiumContent='29.8', CarbohydrateContent='37.1', FiberContent='3.6', SugarContent='30.2', ProteinContent='3.2', RecipeServings='4', RecipeYield='NA', RecipeInstructions='c("Toss 2 cups berries with sugar.", "Let stand for 45 minutes, stirring occasionally.", "Transfer berry-sugar mixture to food processor.", "Add yogurt and process until smooth.", "Strain through fine sieve. Pour into baking pan (or transfer to ice cream maker and process according to manufacturers\' directions). Freeze uncovered until edges are solid but centre is soft.  Transfer to processor and blend until smooth again.", "Return to pan and freeze until edges are solid.", "Transfer to processor and blend until smooth again.", \n"Fold in remaining 2 cups of blueberries.", "Pour into plastic mold and freeze overnight. Let soften slightly to serve.")'),
 Row(RecipeId='39', Name='Biryani', AuthorId='1567', AuthorName='elly9812', CookTime='PT25M', PrepTime='PT4H', TotalTime='PT4H25M', DatePublished='1999-08-29T13:12:00Z', Description='Make and share this Biryani recipe from Food.com.', Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/39/picM9Mhnw.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/39/picHv4Ocr.jpg")', RecipeCategory='Chicken Breast', Keywords='c("Chicken Thigh & Leg", "Chicken", "Poultry", "Meat", "Asian", "Indian", "Weeknight", "Stove Top")', RecipeIngredientQuantities='c("1", "4", "2", "2", "8", "1/4", "8", "1/2", "1", "1", "1/4", "1/4", "1/2", "1/4", "2", "3", NA, "2", "1", "1", "8", "2", "1/3", "1/3", "1/3", "6")', RecipeIngredientParts='c("saffron", "milk", "hot green chili peppers", "onions", "garlic", "clove", "peppercorns", "cardamom seed", "cumin seed", "poppy seed", "mace", "cilantro", "mint leaf", "fresh lemon juice", "plain yogurt", "boneless chicken", "salt", "ghee", "onion", "tomatoes", "basmati rice", "long-grain rice", "raisins", "cashews", "eggs")', AggregatedRating='3', ReviewCount='1', Calories='1110.7', FatContent='58.8', SaturatedFatContent='16.6', CholesterolContent='372.8', SodiumContent='368.4', CarbohydrateContent='84.4', FiberContent='9', SugarContent='20.4', ProteinContent='63.4', RecipeServings='6', RecipeYield='NA', RecipeInstructions='c("Soak saffron in warm milk for 5 minutes and puree in blender.", "Add chiles, onions, ginger, garlic, cloves, peppercorns, cardamom seeds, cinnamon, coriander and cumin seeds, poppy seeds, nutmeg, mace, cilantro or mint leaves and lemon juice. Blend into smooth paste. Put paste into large bowl, add yogurt and mix well.", "Marinate chicken in yogurt mixture with salt, covered for at least 2 - 6 hours in refrigerator.", "In skillet. heat oil over medium heat for 1 minute. Add ghee and 15 seconds later add onion and fry for about8 minutes.", \n"Reserve for garnish.", "In same skillet, cook chicken with its marinade with tomatoes for about 10 minutes over medium heat, uncovered.", "Remove chicken pieces from the sauce and set aside. Add rice to sauce, bring to boil, and cook, covered over low heat for 15 minutes.", "Return chicken and add raisins, cashews and almonds; mix well.", "Simmer, covered for 5 minutes.", "Place chicken, eggs and rice in large serving dish in such a way that yellow of the eggs, the saffron-colored rice, the nuts and the chicken make a colorful display.", \n"Add reserved onion as garnish.")')]

[Row(RecipeId='38', Name='Low-Fat Berry Blue Frozen Dessert', AuthorId='1533', AuthorName='Dancer', CookTime='PT24H', PrepTime='PT45M', TotalTime='PT24H45M', DatePublished='1999-08-09T21:46:00Z', Description='Make and share this Low-Fat Berry Blue Frozen Dessert recipe from Food.com.', Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/YUeirxMLQaeE1h3v3qnM_229%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/AFPDDHATWzQ0b1CDpDAT_255%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/UYgf9nwMT2SGGJCuzILO_228%20berry%20blue%20frzn%20dess.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/PeBMJN2TGSaYks2759BA_20140722_202142.jpg", \n"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/picuaETeN.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/pictzvxW5.jpg")', RecipeCategory='Frozen Desserts', Keywords='c("Dessert", "Low Protein", "Low Cholesterol", "Healthy", "Free Of...", "Summer", "Weeknight", "Freezer", "Easy")', RecipeIngredientQuantities='c("4", "1/4", "1", "1")', RecipeIngredientParts='c("blueberries", "granulated sugar", "vanilla yogurt", "lemon juice")', AggregatedRating='4.5', ReviewCount='4', Calories='170.9', FatContent='2.5', SaturatedFatContent='1.3', CholesterolContent='8', SodiumContent='29.8', CarbohydrateContent='37.1', FiberContent='3.6', SugarContent='30.2', ProteinContent='3.2', RecipeServings='4', RecipeYield='NA', RecipeInstructions='c("Toss 2 cups berries with sugar.", "Let stand for 45 minutes, stirring occasionally.", "Transfer berry-sugar mixture to food processor.", "Add yogurt and process until smooth.", "Strain through fine sieve. Pour into baking pan (or transfer to ice cream maker and process according to manufacturers\' directions). Freeze uncovered until edges are solid but centre is soft.  Transfer to processor and blend until smooth again.", "Return to pan and freeze until edges are solid.", "Transfer to processor and blend until smooth again.", \n"Fold in remaining 2 cups of blueberries.", "Pour into plastic mold and freeze overnight. Let soften slightly to serve.")'),
 Row(RecipeId='39', Name='Biryani', AuthorId='1567', AuthorName='elly9812', CookTime='PT25M', PrepTime='PT4H', TotalTime='PT4H25M', DatePublished='1999-08-29T13:12:00Z', Description='Make and share this Biryani recipe from Food.com.', Images='c("https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/39/picM9Mhnw.jpg", "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/39/picHv4Ocr.jpg")', RecipeCategory='Chicken Breast', Keywords='c("Chicken Thigh & Leg", "Chicken", "Poultry", "Meat", "Asian", "Indian", "Weeknight", "Stove Top")', RecipeIngredientQuantities='c("1", "4", "2", "2", "8", "1/4", "8", "1/2", "1", "1", "1/4", "1/4", "1/2", "1/4", "2", "3", NA, "2", "1", "1", "8", "2", "1/3", "1/3", "1/3", "6")', RecipeIngredientParts='c("saffron", "milk", "hot green chili peppers", "onions", "garlic", "clove", "peppercorns", "cardamom seed", "cumin seed", "poppy seed", "mace", "cilantro", "mint leaf", "fresh lemon juice", "plain yogurt", "boneless chicken", "salt", "ghee", "onion", "tomatoes", "basmati rice", "long-grain rice", "raisins", "cashews", "eggs")', AggregatedRating='3', ReviewCount='1', Calories='1110.7', FatContent='58.8', SaturatedFatContent='16.6', CholesterolContent='372.8', SodiumContent='368.4', CarbohydrateContent='84.4', FiberContent='9', SugarContent='20.4', ProteinContent='63.4', RecipeServings='6', RecipeYield='NA', RecipeInstructions='c("Soak saffron in warm milk for 5 minutes and puree in blender.", "Add chiles, onions, ginger, garlic, cloves, peppercorns, cardamom seeds, cinnamon, coriander and cumin seeds, poppy seeds, nutmeg, mace, cilantro or mint leaves and lemon juice. Blend into smooth paste. Put paste into large bowl, add yogurt and mix well.", "Marinate chicken in yogurt mixture with salt, covered for at least 2 - 6 hours in refrigerator.", "In skillet. heat oil over medium heat for 1 minute. Add ghee and 15 seconds later add onion and fry for about8 minutes.", \n"Reserve for garnish.", "In same skillet, cook chicken with its marinade with tomatoes for about 10 minutes over medium heat, uncovered.", "Remove chicken pieces from the sauce and set aside. Add rice to sauce, bring to boil, and cook, covered over low heat for 15 minutes.", "Return chicken and add raisins, cashews and almonds; mix well.", "Simmer, covered for 5 minutes.", "Place chicken, eggs and rice in large serving dish in such a way that yellow of the eggs, the saffron-colored rice, the nuts and the chicken make a colorful display.", \n"Add reserved onion as garnish.")')]

- `take(2)`  
  ดึง 2 แถวแรกออกมาเป็น list ของ Row คล้าย `head()`

## 5. เลือกเฉพาะ Column ที่จะใช้

In [68]:
recipes_small = recipes_df.select(
    "RecipeId",
    "Name",
    "RecipeCategory",
    "CookTime",
    "PrepTime",
    "TotalTime",
    "RecipeServings",
    "RecipeIngredientParts",
    "Calories"
)

reviews_small = reviews_df.select(
    "RecipeId",
    "AuthorId",
    "Rating",
    "Review",
    "DateSubmitted"
)

- `select(...)`  
  เลือกเฉพาะ column ที่ต้องการใช้

- `recipes_small`  
  DataFrame ของข้อมูลสูตรอาหารแบบลด column แล้ว

- `reviews_small`  
  DataFrame ของข้อมูล review แบบลด column แล้ว



> Spark DataFrame เป็น immutable
คือคำสั่งพวกนี้จะสร้าง DataFrame ใหม่ไม่ได้ไปแก้ของเดิม

## 6. แปลงชนิดข้อมูล + Clean ข้อมูล

In [69]:
from pyspark.sql import functions as F

recipes_clean = (
    recipes_small
    .withColumn("RecipeId", F.col("RecipeId").cast("int"))
    .withColumn("Calories", F.expr("try_cast(Calories as double)"))
    .dropna(subset=["RecipeId"])
    .dropDuplicates(["RecipeId"])
)

reviews_clean = (
    reviews_small
    .withColumn("RecipeId", F.col("RecipeId").cast("int"))
    .withColumn("Rating", F.col("Rating").cast("double"))
    .dropna(subset=["RecipeId", "Rating"])
)

- `from pyspark.sql import functions as F`  
  import function ที่ใช้บ่อยใน Spark เช่น `col`, `avg`, `count`, `when`

- `withColumn("RecipeId", F.col("RecipeId").cast("int"))`  
  แปลง `RecipeId` เป็น integer

- `withColumn("Calories", F.col("Calories").cast("double"))`  
  แปลง `Calories` เป็นเลขทศนิยม

- `withColumn("Rating", F.col("Rating").cast("double"))`  
  แปลง `Rating` เป็นเลขทศนิยม

- `dropna(subset=[...])`  
  ลบ row ที่ column สำคัญเป็น null

- `dropDuplicates(["RecipeId"])`  
  ลบที่มี `RecipeId` ซ้ำ

In [70]:
recipes_clean.printSchema()
reviews_clean.printSchema()

root
 |-- RecipeId: integer (nullable = true)
 |-- Name: string (nullable = true)
 |-- RecipeCategory: string (nullable = true)
 |-- CookTime: string (nullable = true)
 |-- PrepTime: string (nullable = true)
 |-- TotalTime: string (nullable = true)
 |-- RecipeServings: string (nullable = true)
 |-- RecipeIngredientParts: string (nullable = true)
 |-- Calories: double (nullable = true)

root
 |-- RecipeId: integer (nullable = true)
 |-- AuthorId: string (nullable = true)
 |-- Rating: double (nullable = true)
 |-- Review: string (nullable = true)
 |-- DateSubmitted: string (nullable = true)

root
 |-- RecipeId: integer (nullable = true)
 |-- Name: string (nullable = true)
 |-- RecipeCategory: string (nullable = true)
 |-- CookTime: string (nullable = true)
 |-- PrepTime: string (nullable = true)
 |-- TotalTime: string (nullable = true)
 |-- RecipeServings: string (nullable = true)
 |-- RecipeIngredientParts: string (nullable = true)
 |-- Calories: double (nullable = true)

root
 |-- RecipeId: integer (nullable = true)
 |-- AuthorId: string (nullable = true)
 |-- Rating: double (nullable = true)
 |-- Review: string (nullable = true)
 |-- DateSubmitted: string (nullable = true)

เช็ก schema อีกครั้งว่า column ที่ต้องใช้คำนวณถูกแปลงเป็นตัวเลขแล้วหรือยัง

In [71]:
from pyspark.sql import functions as F

recipes_clean = (
    recipes_small
    .withColumn("RecipeId", F.expr("try_cast(RecipeId as int)"))
    .withColumn("Calories", F.regexp_replace("Calories", "[^0-9.]", ""))
    .withColumn("Calories", F.expr("try_cast(Calories as double)"))
    .dropna(subset=["RecipeId"])
    .dropDuplicates(["RecipeId"])
)

reviews_clean = (
    reviews_small
    .withColumn("RecipeId", F.expr("try_cast(RecipeId as int)"))
    .withColumn("Rating", F.expr("try_cast(Rating as double)"))
    .dropna(subset=["RecipeId", "Rating"])
)

## 7. ดูสถิติเบื้องต้นด้วย describe

In [72]:
recipes_clean.describe(["Calories"]).show()

+-------+------------------+
|summary|          Calories|
+-------+------------------+
|  count|            522517|
|   mean|484.43857998878127|
| stddev|1397.1166490876112|
|    min|               0.0|
|    max|          612854.6|
+-------+------------------+

+-------+------------------+
|summary|          Calories|
+-------+------------------+
|  count|            522517|
|   mean|484.43857998878127|
| stddev|1397.1166490876112|
|    min|               0.0|
|    max|          612854.6|
+-------+------------------+

- `describe(["Calories"])`  
  ดูสถิติของ column `Calories`

In [73]:
reviews_clean.describe(["Rating"]).show()

+-------+------------------+
|summary|            Rating|
+-------+------------------+
|  count|           1401982|
|   mean| 4.407951029328479|
| stddev|1.2720116809642992|
|    min|               0.0|
|    max|               5.0|
+-------+------------------+

+-------+------------------+
|summary|            Rating|
+-------+------------------+
|  count|           1401982|
|   mean| 4.407951029328479|
| stddev|1.2720116809642992|
|    min|               0.0|
|    max|               5.0|
+-------+------------------+

ใช้ดูภาพรวมคะแนน review เช่น ค่าเฉลี่ย ต่ำสุด สูงสุด

## 8. นับค่าที่ไม่ซ้ำด้วย distinct

In [74]:
recipes_clean.select("RecipeCategory").distinct().count()

312

312

- `select("RecipeCategory")`  
  เลือกเฉพาะ column หมวดหมู่

- `distinct()`  
  เอาค่าที่ไม่ซ้ำ

- `count()`  
  นับจำนวน category ที่ไม่ซ้ำ

In [75]:
reviews_clean.select("RecipeId").distinct().count()

271678

271678

ใช้ดูว่าใน review มีสูตรอาหารกี่สูตรที่ถูกรีวิวอย่างน้อย 1 ครั้ง

## 9. Filter

In [76]:
high_rating_reviews = reviews_clean.filter(F.col("Rating") >= 4)
high_rating_reviews.show(5)

+--------+--------+------+--------------------+--------------------+
|RecipeId|AuthorId|Rating|              Review|       DateSubmitted|
+--------+--------+------+--------------------+--------------------+
|     992|    2008|   5.0|better than any y...|2000-01-25T21:44:00Z|
|    4384|    1634|   4.0|I cut back on the...|2001-10-17T16:49:59Z|
|    7435|    1773|   5.0|easily the best i...|2000-03-13T21:15:00Z|
|      44|    2085|   5.0|  An excellent dish.|2000-03-28T12:51:00Z|
|    5221|    2046|   4.0|love it, but with...|2000-05-08T11:08:00Z|
+--------+--------+------+--------------------+--------------------+
only showing top 5 rows
+--------+--------+------+--------------------+--------------------+
|RecipeId|AuthorId|Rating|              Review|       DateSubmitted|
+--------+--------+------+--------------------+--------------------+
|     992|    2008|   5.0|better than any y...|2000-01-25T21:44:00Z|
|    4384|    1634|   4.0|I cut back on the...|2001-10-17T16:49:59Z|
|    7435|    1773|   5.0|easily the best i...|2000-03-13T21:15:00Z|
|      44|    2085|   5.0|  An excellent dish.|2000-03-28T12:51:00Z|
|    5221|    2046|   4.0|love it, but with...|2000-05-08T11:08:00Z|
+--------+--------+------+--------------------+--------------------+
only showing top 5 rows

- `filter(F.col("Rating") >= 4)`  
  เลือกเฉพาะ review ที่ rating มากกว่าหรือเท่ากับ 4

- `show(5)`  
  แสดงผล 5 แถวแรก

## 10. when / otherwise

> สร้าง column จากเงื่อนไข

In [77]:
reviews_labeled = reviews_clean.withColumn(
    "rating_label",
    F.when(F.col("Rating") >= 4, "good")
     .when(F.col("Rating") >= 2, "normal")
     .otherwise("bad")
)

reviews_labeled.select("RecipeId", "Rating", "rating_label").show(10)

+--------+------+------------+
|RecipeId|Rating|rating_label|
+--------+------+------------+
|     992|   5.0|        good|
|    4384|   4.0|        good|
|    4523|   2.0|      normal|
|    7435|   5.0|        good|
|      44|   5.0|        good|
|    5221|   4.0|        good|
|   13307|   5.0|        good|
|     148|   0.0|         bad|
|     517|   5.0|        good|
|    4684|   5.0|        good|
+--------+------+------------+
only showing top 10 rows
+--------+------+------------+
|RecipeId|Rating|rating_label|
+--------+------+------------+
|     992|   5.0|        good|
|    4384|   4.0|        good|
|    4523|   2.0|      normal|
|    7435|   5.0|        good|
|      44|   5.0|        good|
|    5221|   4.0|        good|
|   13307|   5.0|        good|
|     148|   0.0|         bad|
|     517|   5.0|        good|
|    4684|   5.0|        good|
+--------+------+------------+
only showing top 10 rows

- `withColumn("rating_label", ...)`  
  สร้าง column ใหม่ชื่อ `rating_label`

- `F.when(F.col("Rating") >= 4, "good")`  
  ถ้า rating >= 4 ให้เป็น good

- `.when(F.col("Rating") >= 2, "normal")`  
  ถ้า rating >= 2 ให้เป็น normal

- `.otherwise("bad")`  
  ถ้าไม่เข้าเงื่อนไขก่อนหน้า ให้เป็น bad

## 11. like / contains / startswith / endswith ใช้ค้นหาข้อความ

In [78]:
recipes_clean.select(
    "Name",
    F.col("Name").like("%Chicken%").alias("has_chicken_in_name")
).show(10, truncate=False)

+------------------------------+-------------------+
|Name                          |has_chicken_in_name|
+------------------------------+-------------------+
|Best Lemonade                 |false              |
|Carina's Tofu-Vegetable Kebabs|false              |
|Best Blackbottom Pie          |false              |
|Warm Chicken A La King        |true               |
|Butter Pecan Cookies          |false              |
|Boston Cream Pie              |false              |
|Cafe Cappuccino               |false              |
|Jimmy G's Carrot Cake         |false              |
|Carrot Cake                   |false              |
|Black Bean Salsa              |false              |
+------------------------------+-------------------+
only showing top 10 rows
+------------------------------+-------------------+
|Name                          |has_chicken_in_name|
+------------------------------+-------------------+
|Best Lemonade                 |false              |
|Carina's Tofu-Vegetable Kebabs|false              |
|Best Blackbottom Pie          |false              |
|Warm Chicken A La King        |true               |
|Butter Pecan Cookies          |false              |
|Boston Cream Pie              |false              |
|Cafe Cappuccino               |false              |
|Jimmy G's Carrot Cake         |false              |
|Carrot Cake                   |false              |
|Black Bean Salsa              |false              |
+------------------------------+-------------------+
only showing top 10 rows

- `like("%Chicken%")`  
  ตรวจว่าชื่อเมนูมีคำว่า Chicken หรือไม่

- `%`  
  หมายถึงมีตัวอักษรอะไรก่อนหรือหลังก็ได้

In [79]:
recipes_clean.filter(
    F.lower(F.col("RecipeIngredientParts")).contains("chicken")
).select(
    "Name",
    "RecipeIngredientParts"
).show(10, truncate=False)

+-------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|Name                                             |RecipeIngredientParts                                                                                                                                                                                                                                                                                                                                  |
+-------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|Warm Chicken A La King                           |c("chicken", "butter", "flour", "milk", "celery", "button mushrooms", "green pepper", "canned pimiento", "salt", "black pepper", "Worcestershire sauce", "parsley")                                                                                                                                                                                    |
|Brown Rice and Vegetable Pilaf                   |c("brown rice", "chicken broth", "unsalted butter", "oregano", "marjoram", "summer savory", "unsalted butter", "celery", "fresh snow pea", "broccoli floret", "green onion", "lemons", "coconut")                                                                                                                                                      |
|Braised Chicken with Onions and Tomatoes         |c("onions", "gingerroot", "garlic", "green serrano chilies", "tomatoes", "black cardamom pods", "cinnamon sticks", "cloves", "black peppercorns", "bay leaves", "cumin", "cayenne pepper", "turmeric", "plain yogurt", "dark rum", "salt", "cilantro", "chicken pieces")                                                                               |
|Chicken and Broccoli Lasagna                     |c("butter", "flour", "milk", "chicken broth", "eggs", "parmesan cheese", "butter", "onion", "garlic", "chicken", "broccoli", "parsley", "mozzarella cheese", "parmesan cheese", "salt", "nutmeg")                                                                                                                                                      |
|Chicken and Pineapple Salad With Curry Mayonnaise|c("barbecued chicken", "coconut", "unsweetened pineapple slices", "spring onions", "curry powder", "five-spice powder", "garlic clove", "fresh ginger", "mayonnaise", "coconut milk")                                                                                                                                                                  |
|Light Cucumber Soup                              |c("cucumbers", "nonfat sour cream", "low sodium chicken broth", "onion", "fresh parsley", "fresh dill", "dill weed", "lemon juice", "white pepper")                                                                                                                                                                                                    |
|Chicken Curry                                    |c("cumin seeds", "red pepper flakes", "turmeric", "ginger", "clove", "salt", "black pepper", "boneless skinless chicken breasts", "butter", "fresh ginger", "garlic", "onions", "cinnamon sticks", "bay leaf", "cardamom pods", "whole canned tomatoes", "plain yogurt", "golden raisin", "fresh cilantro", "basmati rice", "cashews", "mango chutney")|
|Chicken Liver Pate                               |c("butter", "cream cheese", "chicken liver", "onion", "chicken broth", "brandy", "paprika", "salt", "cayenne pepper")                                                                                                                                                                                                                                  |
|Chicken Liver Pate II                            |c("chicken livers", "heavy cream", "butter", "onion", "garlic", "allspice", "bay leaf", "peppercorn", "dried funghi porcini", "white mushrooms", "madeira wine", "cognac", "shallot")                                                                                                                                                                  |
|Chicken Sate with Peanut Sauce                   |c("boneless skinless chicken breast halves", "soy sauce", "lime juice", "butter", "onion", "olive oil", "cayenne", "soy sauce", "sugar", "garlic", "ginger", "salt", "lime juice")                                                                                                                                                                     |
+-------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 10 rows
+-------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|Name                                             |RecipeIngredientParts                                                                                                                                                                                                                                                                                                                                  |
+-------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|Warm Chicken A La King                           |c("chicken", "butter", "flour", "milk", "celery", "button mushrooms", "green pepper", "canned pimiento", "salt", "black pepper", "Worcestershire sauce", "parsley")                                                                                                                                                                                    |
|Brown Rice and Vegetable Pilaf                   |c("brown rice", "chicken broth", "unsalted butter", "oregano", "marjoram", "summer savory", "unsalted butter", "celery", "fresh snow pea", "broccoli floret", "green onion", "lemons", "coconut")                                                                                                                                                      |
|Braised Chicken with Onions and Tomatoes         |c("onions", "gingerroot", "garlic", "green serrano chilies", "tomatoes", "black cardamom pods", "cinnamon sticks", "cloves", "black peppercorns", "bay leaves", "cumin", "cayenne pepper", "turmeric", "plain yogurt", "dark rum", "salt", "cilantro", "chicken pieces")                                                                               |
|Chicken and Broccoli Lasagna                     |c("butter", "flour", "milk", "chicken broth", "eggs", "parmesan cheese", "butter", "onion", "garlic", "chicken", "broccoli", "parsley", "mozzarella cheese", "parmesan cheese", "salt", "nutmeg")                                                                                                                                                      |
|Chicken and Pineapple Salad With Curry Mayonnaise|c("barbecued chicken", "coconut", "unsweetened pineapple slices", "spring onions", "curry powder", "five-spice powder", "garlic clove", "fresh ginger", "mayonnaise", "coconut milk")                                                                                                                                                                  |
|Light Cucumber Soup                              |c("cucumbers", "nonfat sour cream", "low sodium chicken broth", "onion", "fresh parsley", "fresh dill", "dill weed", "lemon juice", "white pepper")                                                                                                                                                                                                    |
|Chicken Curry                                    |c("cumin seeds", "red pepper flakes", "turmeric", "ginger", "clove", "salt", "black pepper", "boneless skinless chicken breasts", "butter", "fresh ginger", "garlic", "onions", "cinnamon sticks", "bay leaf", "cardamom pods", "whole canned tomatoes", "plain yogurt", "golden raisin", "fresh cilantro", "basmati rice", "cashews", "mango chutney")|
|Chicken Liver Pate                               |c("butter", "cream cheese", "chicken liver", "onion", "chicken broth", "brandy", "paprika", "salt", "cayenne pepper")                                                                                                                                                                                                                                  |
|Chicken Liver Pate II                            |c("chicken livers", "heavy cream", "butter", "onion", "garlic", "allspice", "bay leaf", "peppercorn", "dried funghi porcini", "white mushrooms", "madeira wine", "cognac", "shallot")                                                                                                                                                                  |
|Chicken Sate with Peanut Sauce                   |c("boneless skinless chicken breast halves", "soy sauce", "lime juice", "butter", "onion", "olive oil", "cayenne", "soy sauce", "sugar", "garlic", "ginger", "salt", "lime juice")                                                                                                                                                                     |
+-------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 10 rows

- `F.lower(...)`  
  แปลงข้อความเป็นตัวเล็กก่อนค้นหา

- `.contains("chicken")`  
  เช็กว่ามีคำว่า "chicken" อยู่ใน ingredient หรือไม่

In [80]:
recipes_clean.select(
    "Name",
    F.col("Name").startswith("Chicken").alias("start_with_chicken"),
    F.col("Name").endswith("Soup").alias("end_with_soup")
).show(10, truncate=False)

+------------------------------+------------------+-------------+
|Name                          |start_with_chicken|end_with_soup|
+------------------------------+------------------+-------------+
|Best Lemonade                 |false             |false        |
|Carina's Tofu-Vegetable Kebabs|false             |false        |
|Best Blackbottom Pie          |false             |false        |
|Warm Chicken A La King        |false             |false        |
|Butter Pecan Cookies          |false             |false        |
|Boston Cream Pie              |false             |false        |
|Cafe Cappuccino               |false             |false        |
|Jimmy G's Carrot Cake         |false             |false        |
|Carrot Cake                   |false             |false        |
|Black Bean Salsa              |false             |false        |
+------------------------------+------------------+-------------+
only showing top 10 rows
+------------------------------+------------------+-------------+
|Name                          |start_with_chicken|end_with_soup|
+------------------------------+------------------+-------------+
|Best Lemonade                 |false             |false        |
|Carina's Tofu-Vegetable Kebabs|false             |false        |
|Best Blackbottom Pie          |false             |false        |
|Warm Chicken A La King        |false             |false        |
|Butter Pecan Cookies          |false             |false        |
|Boston Cream Pie              |false             |false        |
|Cafe Cappuccino               |false             |false        |
|Jimmy G's Carrot Cake         |false             |false        |
|Carrot Cake                   |false             |false        |
|Black Bean Salsa              |false             |false        |
+------------------------------+------------------+-------------+
only showing top 10 rows

- `startswith("Chicken")`  
  เช็กว่าชื่อเมนูขึ้นต้นด้วย Chicken หรือไม่

- `endswith("Soup")`  
  เช็กว่าชื่อเมนูลงท้ายด้วย Soup หรือไม่

## 12. substr
> ตัดข้อความบางส่วน

In [81]:
recipes_clean.select(
    "Name",
    F.col("Name").substr(1, 10).alias("short_name")
).show(10, truncate=False)

+------------------------------+----------+
|Name                          |short_name|
+------------------------------+----------+
|Best Lemonade                 |Best Lemon|
|Carina's Tofu-Vegetable Kebabs|Carina's T|
|Best Blackbottom Pie          |Best Black|
|Warm Chicken A La King        |Warm Chick|
|Butter Pecan Cookies          |Butter Pec|
|Boston Cream Pie              |Boston Cre|
|Cafe Cappuccino               |Cafe Cappu|
|Jimmy G's Carrot Cake         |Jimmy G's |
|Carrot Cake                   |Carrot Cak|
|Black Bean Salsa              |Black Bean|
+------------------------------+----------+
only showing top 10 rows
+------------------------------+----------+
|Name                          |short_name|
+------------------------------+----------+
|Best Lemonade                 |Best Lemon|
|Carina's Tofu-Vegetable Kebabs|Carina's T|
|Best Blackbottom Pie          |Best Black|
|Warm Chicken A La King        |Warm Chick|
|Butter Pecan Cookies          |Butter Pec|
|Boston Cream Pie              |Boston Cre|
|Cafe Cappuccino               |Cafe Cappu|
|Jimmy G's Carrot Cake         |Jimmy G's |
|Carrot Cake                   |Carrot Cak|
|Black Bean Salsa              |Black Bean|
+------------------------------+----------+
only showing top 10 rows

- `substr(1, 10)`  
  ตัดข้อความจากตำแหน่งที่ 1 จำนวน 10 ตัวอักษร

- `alias("short_name")`  
  ตั้งชื่อ column ใหม่

## 13. between เลือกค่าที่อยู่ในช่วง

In [82]:
recipes_clean.filter(
    F.col("Calories").isNotNull()
).select(
    "Name",
    "Calories",
    F.col("Calories").between(100, 500).alias("calories_100_to_500")
).show(10, truncate=False)

+------------------------------+--------+-------------------+
|Name                          |Calories|calories_100_to_500|
+------------------------------+--------+-------------------+
|Best Lemonade                 |311.1   |true               |
|Carina's Tofu-Vegetable Kebabs|536.1   |false              |
|Best Blackbottom Pie          |437.9   |true               |
|Warm Chicken A La King        |895.5   |false              |
|Butter Pecan Cookies          |69.0    |false              |
|Boston Cream Pie              |688.2   |false              |
|Cafe Cappuccino               |62.2    |false              |
|Jimmy G's Carrot Cake         |372.9   |true               |
|Carrot Cake                   |522.6   |false              |
|Black Bean Salsa              |114.3   |true               |
+------------------------------+--------+-------------------+
only showing top 10 rows
+------------------------------+--------+-------------------+
|Name                          |Calories|calories_100_to_500|
+------------------------------+--------+-------------------+
|Best Lemonade                 |311.1   |true               |
|Carina's Tofu-Vegetable Kebabs|536.1   |false              |
|Best Blackbottom Pie          |437.9   |true               |
|Warm Chicken A La King        |895.5   |false              |
|Butter Pecan Cookies          |69.0    |false              |
|Boston Cream Pie              |688.2   |false              |
|Cafe Cappuccino               |62.2    |false              |
|Jimmy G's Carrot Cake         |372.9   |true               |
|Carrot Cake                   |522.6   |false              |
|Black Bean Salsa              |114.3   |true               |
+------------------------------+--------+-------------------+
only showing top 10 rows

- `between(100, 500)`  
  เช็กว่า calories อยู่ระหว่าง 100 ถึง 500 หรือไม่

ผลลัพธ์เป็น boolean

In [83]:
recipes_clean.filter(
    F.col("Calories").between(100, 500)
).select(
    "Name",
    "Calories"
).show(10, truncate=False)

+------------------------------+--------+
|Name                          |Calories|
+------------------------------+--------+
|Best Lemonade                 |311.1   |
|Best Blackbottom Pie          |437.9   |
|Jimmy G's Carrot Cake         |372.9   |
|Black Bean Salsa              |114.3   |
|Almond Pound Cake             |408.5   |
|Brownie Pudding               |182.8   |
|Alfredo Sauce                 |489.9   |
|Buttermilk Ranch Dressing     |267.2   |
|Butter Madeira Cake           |373.8   |
|Brown Rice and Vegetable Pilaf|412.6   |
+------------------------------+--------+
only showing top 10 rows
+------------------------------+--------+
|Name                          |Calories|
+------------------------------+--------+
|Best Lemonade                 |311.1   |
|Best Blackbottom Pie          |437.9   |
|Jimmy G's Carrot Cake         |372.9   |
|Black Bean Salsa              |114.3   |
|Almond Pound Cake             |408.5   |
|Brownie Pudding               |182.8   |
|Alfredo Sauce                 |489.9   |
|Buttermilk Ranch Dressing     |267.2   |
|Butter Madeira Cake           |373.8   |
|Brown Rice and Vegetable Pilaf|412.6   |
+------------------------------+--------+
only showing top 10 rows

ใช้ `between` เป็นเงื่อนไขใน `filter`  
เพื่อเอาเฉพาะสูตรที่ calories อยู่ในช่วง 100 ถึง 500

## 14. เพิ่ม ลบ เปลี่ยนชื่อ Column

In [84]:
recipes_with_calorie_group = recipes_clean.withColumn(
    "calorie_group",
    F.when(F.col("Calories") < 200, "low")
     .when(F.col("Calories") < 500, "medium")
     .otherwise("high")
)

recipes_with_calorie_group.select(
    "Name",
    "Calories",
    "calorie_group"
).show(10, truncate=False)

+------------------------------+--------+-------------+
|Name                          |Calories|calorie_group|
+------------------------------+--------+-------------+
|Best Lemonade                 |311.1   |medium       |
|Carina's Tofu-Vegetable Kebabs|536.1   |high         |
|Best Blackbottom Pie          |437.9   |medium       |
|Warm Chicken A La King        |895.5   |high         |
|Butter Pecan Cookies          |69.0    |low          |
|Boston Cream Pie              |688.2   |high         |
|Cafe Cappuccino               |62.2    |low          |
|Jimmy G's Carrot Cake         |372.9   |medium       |
|Carrot Cake                   |522.6   |high         |
|Black Bean Salsa              |114.3   |low          |
+------------------------------+--------+-------------+
only showing top 10 rows
+------------------------------+--------+-------------+
|Name                          |Calories|calorie_group|
+------------------------------+--------+-------------+
|Best Lemonade                 |311.1   |medium       |
|Carina's Tofu-Vegetable Kebabs|536.1   |high         |
|Best Blackbottom Pie          |437.9   |medium       |
|Warm Chicken A La King        |895.5   |high         |
|Butter Pecan Cookies          |69.0    |low          |
|Boston Cream Pie              |688.2   |high         |
|Cafe Cappuccino               |62.2    |low          |
|Jimmy G's Carrot Cake         |372.9   |medium       |
|Carrot Cake                   |522.6   |high         |
|Black Bean Salsa              |114.3   |low          |
+------------------------------+--------+-------------+
only showing top 10 rows

- `withColumn("calorie_group", ...)`  
  เพิ่ม column ใหม่

- ถ้า Calories < 200 ให้เป็น low
- ถ้า Calories < 500 ให้เป็น medium
- นอกนั้นให้เป็น high

In [85]:
recipes_drop_example = recipes_with_calorie_group.drop("CookTime", "PrepTime")
recipes_drop_example.columns

['RecipeId',
 'Name',
 'RecipeCategory',
 'TotalTime',
 'RecipeServings',
 'RecipeIngredientParts',
 'Calories',
 'calorie_group']

['RecipeId',
 'Name',
 'RecipeCategory',
 'TotalTime',
 'RecipeServings',
 'RecipeIngredientParts',
 'Calories',
 'calorie_group']

- `drop("CookTime", "PrepTime")`  
  ลบ column ที่ไม่ต้องการออก

ไม่ได้ลบจาก DataFrame เดิม แต่สร้าง DataFrame ใหม่

In [86]:
recipes_rename_example = recipes_with_calorie_group.withColumnRenamed(
    "RecipeCategory",
    "Category"
)

recipes_rename_example.columns

['RecipeId',
 'Name',
 'Category',
 'CookTime',
 'PrepTime',
 'TotalTime',
 'RecipeServings',
 'RecipeIngredientParts',
 'Calories',
 'calorie_group']

['RecipeId',
 'Name',
 'Category',
 'CookTime',
 'PrepTime',
 'TotalTime',
 'RecipeServings',
 'RecipeIngredientParts',
 'Calories',
 'calorie_group']

- `withColumnRenamed("RecipeCategory", "Category")`  
  เปลี่ยนชื่อ column จาก `RecipeCategory` เป็น `Category`

## 15. GroupBy + Aggregation

In [87]:
rating_by_recipe = (
    reviews_clean
    .groupBy("RecipeId")
    .agg(
        F.count("*").alias("review_count"),
        F.avg("Rating").alias("avg_rating")
    )
)

- `reviews_clean.groupBy("RecipeId")`  
  รวมข้อมูลรีวิวทั้งหมดโดยจัดกลุ่มตาม `RecipeId` เพื่อให้รีวิวของสูตรเดียวกันอยู่ในกลุ่มเดียวกัน

- `F.count("*")`  
  นับจำนวนรีวิวทั้งหมดในแต่ละกลุ่ม หรือแต่ละสูตรอาหาร

- `.alias("review_count")`  
  ตั้งชื่อ column ใหม่ให้ผลลัพธ์ของการนับว่า `review_count`

- `F.avg("Rating")`  
  คำนวณค่าเฉลี่ยของคะแนน `Rating` ในแต่ละกลุ่ม เพื่อหาคะแนนเฉลี่ยของสูตรนั้น

- `.alias("avg_rating")`  
  ตั้งชื่อ column ใหม่ให้ผลลัพธ์ของค่าเฉลี่ยว่า `avg_rating`

ผลลัพธ์:
- 1 row ต่อ 1 `RecipeId`
- แต่ละสูตรจะมี
  - จำนวนรีวิว (`review_count`)
  - คะแนนเฉลี่ย (`avg_rating`)

In [88]:
rating_by_recipe.orderBy(F.desc("review_count")).show(10)

+--------+------------+------------------+
|RecipeId|review_count|        avg_rating|
+--------+------------+------------------+
|   45809|        2892| 4.314661134163209|
|    2886|        2182| 4.218148487626031|
|   27208|        1614| 4.281908302354399|
|   89204|        1584|4.2228535353535355|
|   39087|        1491| 4.538564721663313|
|   67256|        1359| 4.325974981604121|
|   35813|        1353|4.4368070953436805|
|   54257|        1325| 4.212830188679245|
|   22782|        1273| 4.423409269442263|
|   32204|        1228| 4.521986970684039|
+--------+------------+------------------+
only showing top 10 rows
+--------+------------+------------------+
|RecipeId|review_count|        avg_rating|
+--------+------------+------------------+
|   45809|        2892| 4.314661134163209|
|    2886|        2182| 4.218148487626031|
|   27208|        1614| 4.281908302354399|
|   89204|        1584|4.2228535353535355|
|   39087|        1491| 4.538564721663313|
|   67256|        1359| 4.325974981604121|
|   35813|        1353|4.4368070953436805|
|   54257|        1325| 4.212830188679245|
|   22782|        1273| 4.423409269442263|
|   32204|        1228| 4.521986970684039|
+--------+------------+------------------+
only showing top 10 rows

- `orderBy(F.desc("review_count"))`  
  เรียงจากสูตรที่มีจำนวน review มากที่สุดไปน้อยที่สุด

- `show(10)`  
  แสดง 10 แถวแรก

## 16. Join

In [89]:
recipe_rating = (
    recipes_clean
    .join(rating_by_recipe, on="RecipeId", how="left")
)

- `recipes_clean.join(...)`  
  รวมข้อมูลสูตรอาหารกับข้อมูลคะแนนรีวิว

- `rating_by_recipe`  
  DataFrame ที่มีจำนวนรีวิวและคะแนนเฉลี่ยของแต่ละสูตร

- `on="RecipeId"`  
  ใช้ `RecipeId` เป็น key ในการ join

- `how="left"`  
  เก็บสูตรอาหารทั้งหมดจาก `recipes_clean` ไว้ ถึงแม้บางสูตรจะไม่มี review

ผลลัพธ์:
- ได้ DataFrame ใหม่ชื่อ `recipe_rating`
- แต่ละสูตรจะมีข้อมูล recipe + จำนวน review + คะแนนเฉลี่ย

In [90]:
recipe_rating.select(
    "RecipeId",
    "Name",
    "RecipeCategory",
    "Calories",
    "review_count",
    "avg_rating"
).show(10, truncate=False)

+--------+------------------------------+--------------+--------+------------+-----------------+
|RecipeId|Name                          |RecipeCategory|Calories|review_count|avg_rating       |
+--------+------------------------------+--------------+--------+------------+-----------------+
|40      |Best Lemonade                 |Beverages     |311.1   |9           |4.333333333333333|
|41      |Carina's Tofu-Vegetable Kebabs|Soy/Tofu      |536.1   |2           |4.5              |
|43      |Best Blackbottom Pie          |Pie           |437.9   |1           |1.0              |
|44      |Warm Chicken A La King        |Chicken       |895.5   |22          |4.545454545454546|
|47      |Butter Pecan Cookies          |Dessert       |69.0    |2           |4.0              |
|48      |Boston Cream Pie              |Pie           |688.2   |2           |1.0              |
|52      |Cafe Cappuccino               |Beverages     |62.2    |1           |5.0              |
|53      |Jimmy G's Carrot Cake         |Dessert       |372.9   |1           |3.0              |
|54      |Carrot Cake                   |Dessert       |522.6   |17          |4.235294117647059|
|57      |Black Bean Salsa              |Sauces        |114.3   |NULL        |NULL             |
+--------+------------------------------+--------------+--------+------------+-----------------+
only showing top 10 rows
+--------+-------------------------------------------------+--------------+--------+------------+------------------+
|RecipeId|Name                                             |RecipeCategory|Calories|review_count|avg_rating        |
+--------+-------------------------------------------------+--------------+--------+------------+------------------+
|148     |Bugwiches                                        |Lunch/Snacks  |84.0    |1           |0.0               |
|463     |Cappuccino Coffee Mix                            |Beverages     |54.3    |7           |3.7142857142857144|
|471     |Seared Salmon with Horseradish Tomato Vinaigrette|Summer        |797.3   |3           |3.6666666666666665|
|496     |7-Up Cake                                        |Dessert       |550.2   |1           |5.0               |
|833     |Hamantaschen-Cookies (Haman's Hats)              |Dessert       |89.8    |2           |2.5               |
|1580    |Dutch Buttercake                                 |Dessert       |312.7   |2           |4.5               |
|1591    |Grilled Lemon Chicken                            |Chicken Breast|123.2   |4           |4.25              |
|1959    |Sylvia's Famous Spareribs                        |< 15 Mins     |982.3   |NULL        |NULL              |
|2122    |English Cream Scones                             |Scones        |211.5   |2           |4.0               |
|2142    |Buttery Drop Cookies                             |Drop Cookies  |60.0    |1           |5.0               |
+--------+-------------------------------------------------+--------------+--------+------------+------------------+
only showing top 10 rows

- `recipe_rating.select(...)`  
  เลือกเฉพาะ column ที่ต้องการแสดงจาก DataFrame `recipe_rating`

- `.show(10, truncate=False)`  
  แสดงข้อมูล 10 แถวแรก โดย `truncate=False` ทำให้ข้อความยาว ๆ ไม่ถูกตัด

## 17. วิเคราะห์สูตรที่ popular และ rating สูง

In [91]:
popular_high_rated = (
    recipe_rating
    .filter(F.col("review_count") >= 50)
    .filter(F.col("avg_rating") >= 4.5)
    .orderBy(F.desc("avg_rating"), F.desc("review_count"))
)

popular_high_rated.select(
    "Name",
    "RecipeCategory",
    "avg_rating",
    "review_count",
    "Calories"
).show(20, truncate=False)

+-------------------------------------------------------+--------------+------------------+------------+--------+
|Name                                                   |RecipeCategory|avg_rating        |review_count|Calories|
+-------------------------------------------------------+--------------+------------------+------------+--------+
|Caprese Salad Tomatoes (Italian Marinated Tomatoes)    |Vegetable     |5.0               |52          |137.5   |
|Mexican Stack-Up #RSC                                  |Black Beans   |4.990783410138249 |217         |793.0   |
|Syrup for Blueberry Pancakes                           |Sauces        |4.964912280701754 |57          |376.6   |
|Toffee Dip with Apples                                 |Lunch/Snacks  |4.963636363636364 |55          |1192.6  |
|Make Your Own Boursin Cheese - Paula Deen              |Spreads       |4.962962962962963 |54          |1065.2  |
|Mean's Lamb You Can Eat With a Spoon                   |Lamb/Sheep    |4.96              |50          |1242.8  |
|Mango Salsa #1                                         |Sauces        |4.95945945945946  |74          |409.3   |
|Scott Hibb's Amazing Whiskey Grilled Baby Back Ribs    |Meat          |4.9523809523809526|63          |38680.1 |
|Summer Vegetable Grill Packets #RSC                    |Corn          |4.9411764705882355|51          |232.1   |
|Boboli Pizza Crust Clone                               |Yeast Breads  |4.940298507462686 |67          |285.2   |
|Simply Irresistible Tropical Potato Salad #SP5         |Potato        |4.9324324324324325|74          |398.6   |
|The Best Creole/Cajun Seasoning Mix                    |Cajun         |4.927536231884058 |69          |16.7    |
|Paige's Buttercream Frosting                           |Dessert       |4.925925925925926 |54          |3536.2  |
|Million Dollar Potatoes                                |Potato        |4.918032786885246 |61          |244.8   |
|Italian Sausage, Tomato, and Cream With Bow Ties       |Pork          |4.918032786885246 |61          |919.9   |
|Yummy Oatmeal Chocolate Chip Cookies                   |Drop Cookies  |4.917808219178082 |73          |483.3   |
|Sangria                                                |Beverages     |4.916666666666667 |156         |198.8   |
|Brown Sugar Bundt Cake                                 |Dessert       |4.915966386554622 |119         |637.4   |
|Bread Bowl Potato Soup                                 |Potato        |4.915254237288136 |59          |424.8   |
|You've Got to Be Kidding Me Restaurant Rolls (or Bread)|Breads        |4.915254237288136 |59          |122.5   |
+-------------------------------------------------------+--------------+------------------+------------+--------+
only showing top 20 rows
+-------------------------------------------------------+--------------+------------------+------------+--------+
|Name                                                   |RecipeCategory|avg_rating        |review_count|Calories|
+-------------------------------------------------------+--------------+------------------+------------+--------+
|Caprese Salad Tomatoes (Italian Marinated Tomatoes)    |Vegetable     |5.0               |52          |137.5   |
|Mexican Stack-Up #RSC                                  |Black Beans   |4.990783410138249 |217         |793.0   |
|Syrup for Blueberry Pancakes                           |Sauces        |4.964912280701754 |57          |376.6   |
|Toffee Dip with Apples                                 |Lunch/Snacks  |4.963636363636364 |55          |1192.6  |
|Make Your Own Boursin Cheese - Paula Deen              |Spreads       |4.962962962962963 |54          |1065.2  |
|Mean's Lamb You Can Eat With a Spoon                   |Lamb/Sheep    |4.96              |50          |1242.8  |
|Mango Salsa #1                                         |Sauces        |4.95945945945946  |74          |409.3   |
|Scott Hibb's Amazing Whiskey Grilled Baby Back Ribs    |Meat          |4.9523809523809526|63          |38680.1 |
|Summer Vegetable Grill Packets #RSC                    |Corn          |4.9411764705882355|51          |232.1   |
|Boboli Pizza Crust Clone                               |Yeast Breads  |4.940298507462686 |67          |285.2   |
|Simply Irresistible Tropical Potato Salad #SP5         |Potato        |4.9324324324324325|74          |398.6   |
|The Best Creole/Cajun Seasoning Mix                    |Cajun         |4.927536231884058 |69          |16.7    |
|Paige's Buttercream Frosting                           |Dessert       |4.925925925925926 |54          |3536.2  |
|Italian Sausage, Tomato, and Cream With Bow Ties       |Pork          |4.918032786885246 |61          |919.9   |
|Million Dollar Potatoes                                |Potato        |4.918032786885246 |61          |244.8   |
|Yummy Oatmeal Chocolate Chip Cookies                   |Drop Cookies  |4.917808219178082 |73          |483.3   |
|Sangria                                                |Beverages     |4.916666666666667 |156         |198.8   |
|Brown Sugar Bundt Cake                                 |Dessert       |4.915966386554622 |119         |637.4   |
|Bread Bowl Potato Soup                                 |Potato        |4.915254237288136 |59          |424.8   |
|You've Got to Be Kidding Me Restaurant Rolls (or Bread)|Breads        |4.915254237288136 |59          |122.5   |
+-------------------------------------------------------+--------------+------------------+------------+--------+
only showing top 20 rows

- `filter(F.col("review_count") >= 50)`  
  เลือกสูตรที่มีรีวิวอย่างน้อย 50 ครั้ง

- `filter(F.col("avg_rating") >= 4.5)`  
  เลือกสูตรที่คะแนนเฉลี่ยอย่างน้อย 4.5

- `orderBy(F.desc("avg_rating"), F.desc("review_count"))`  
  เรียงจากคะแนนสูงก่อน แล้วค่อยดูจำนวน review

## 18. วิเคราะห์ตาม Category

In [92]:
category_summary = (
    recipe_rating
    .groupBy("RecipeCategory")
    .agg(
        F.count("*").alias("recipe_count"),
        F.avg("avg_rating").alias("category_avg_rating"),
        F.avg("Calories").alias("avg_calories")
    )
    .orderBy(F.desc("recipe_count"))
)

category_summary.show(20, truncate=False)

+--------------+------------+-------------------+------------------+
|RecipeCategory|recipe_count|category_avg_rating|avg_calories      |
+--------------+------------+-------------------+------------------+
|Dessert       |62072       |4.24364920661682   |643.8104233792989 |
|Lunch/Snacks  |32586       |4.403159714035769  |437.65264530780127|
|One Dish Meal |31345       |4.281247546294441  |529.7373329079594 |
|Vegetable     |27231       |4.41054181697956   |271.88961110499264|
|Breakfast     |21101       |4.353555405940915  |382.85989289607204|
|Beverages     |16076       |4.521560677502436  |283.1140333416283 |
|Chicken       |13249       |4.360758863622481  |536.77809646011   |
|Meat          |13131       |4.283458514874751  |606.2567511994523 |
|Breads        |12804       |4.248610480403898  |618.7491487035314 |
|Pork          |12603       |4.375726736875861  |558.1378878044925 |
|Sauces        |12166       |4.384590219865782  |384.4776837086968 |
|Chicken Breast|11282       |4.37615848975284   |457.83991313597005|
|Potato        |10870       |4.424074260361768  |374.75757129714765|
|Quick Breads  |10387       |4.226220343603107  |617.8289207663424 |
|< 60 Mins     |9719        |4.331251186852883  |451.3011626710569 |
|< 30 Mins     |9020        |4.404099383190223  |399.508470066518  |
|Cheese        |8462        |4.3949716792939455 |450.5187189789648 |
|Pie           |7775        |4.294356169351381  |794.7425209003203 |
|Bar Cookie    |7029        |4.2955989196546085 |465.7541613316261 |
|Low Protein   |6663        |4.367612976980023  |370.5917904847664 |
+--------------+------------+-------------------+------------------+
only showing top 20 rows
+--------------+------------+-------------------+------------------+
|RecipeCategory|recipe_count|category_avg_rating|avg_calories      |
+--------------+------------+-------------------+------------------+
|Dessert       |62072       |4.243649206616812  |643.8104233793013 |
|Lunch/Snacks  |32586       |4.403159714035772  |437.6526453078008 |
|One Dish Meal |31345       |4.281247546294448  |529.7373329079597 |
|Vegetable     |27231       |4.410541816979569  |271.8896111049906 |
|Breakfast     |21101       |4.353555405940917  |382.85989289607124|
|Beverages     |16076       |4.521560677502439  |283.1140333416273 |
|Chicken       |13249       |4.3607588636224826 |536.7780964601101 |
|Meat          |13131       |4.283458514874751  |606.256751199452  |
|Breads        |12804       |4.2486104804039    |618.74914870353   |
|Pork          |12603       |4.375726736875868  |558.1378878044908 |
|Sauces        |12166       |4.384590219865782  |384.47768370869613|
|Chicken Breast|11282       |4.376158489752838  |457.83991313596897|
|Potato        |10870       |4.424074260361769  |374.75757129714816|
|Quick Breads  |10387       |4.226220343603106  |617.8289207663423 |
|< 60 Mins     |9719        |4.331251186852882  |451.3011626710567 |
|< 30 Mins     |9020        |4.404099383190222  |399.50847006651867|
|Cheese        |8462        |4.394971679293944  |450.51871897896524|
|Pie           |7775        |4.294356169351381  |794.7425209003211 |
|Bar Cookie    |7029        |4.295598919654604  |465.754161331626  |
|Low Protein   |6663        |4.367612976980021  |370.59179048476665|
+--------------+------------+-------------------+------------------+
only showing top 20 rows

- `groupBy("RecipeCategory")`  
  จัดกลุ่มข้อมูลตาม"หมวดหมู่อาหาร"

- `F.count("*").alias("recipe_count")`  
  นับจำนวนสูตรในแต่ละหมวด

- `F.avg("avg_rating").alias("category_avg_rating")`  
  คำนวณ rating เฉลี่ยของหมวดนั้น

- `F.avg("Calories").alias("avg_calories")`  
  คำนวณ calories เฉลี่ยของหมวดนั้น

## 19. Sort / OrderBy

In [93]:
recipe_rating.sort(F.col("avg_rating").desc()).show(10, truncate=False)

+--------+----------------------------------------------+--------------+--------+--------+---------+--------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+----------+
|RecipeId|Name                                          |RecipeCategory|CookTime|PrepTime|TotalTime|RecipeServings|RecipeIngredientParts                                                                                                                                                                                     |Calories|review_count|avg_rating|
+--------+----------------------------------------------+--------------+--------+--------+---------+--------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+----------+
|94      |Blueberry Buttertarts                         |Dessert       |PT25M   |PT15M   |PT40M    |12            |c("egg", "corn syrup", "lemon juice", "vanilla", "brown sugar", "all-purpose flour", "blueberries")                                                                                                       |337.9   |4           |5.0       |
|84      |Braised Brussels Sprouts With Vinegar and Dill|Vegetable     |PT23M   |PT25M   |PT48M    |12            |c("Brussels sprouts", "fresh dill", "wine vinegar")                                                                                                                                                       |40.9    |4           |5.0       |
|152     |Angel Food Cake Waldorf                       |Dessert       |NA      |PT1H15M |PT1H15M  |8             |c("sugar", "salt")                                                                                                                                                                                        |613.8   |2           |5.0       |
|89      |Almond Joy Cake                               |Dessert       |PT1H    |PT20M   |PT1H20M  |12            |c("margarine", "milk", "sugar", "marshmallows", "coconut", "sugar", "margarine", "evaporated milk", "vanilla flavoring", "marshmallow creme")                                                             |1001.4  |2           |5.0       |
|115     |A New Spaghetti with Clams                    |Spaghetti     |PT20M   |PT20M   |PT40M    |1             |c("littleneck clams", "extra virgin olive oil", "garlic", "Canadian bacon", "smoked ham", "dry white vermouth", "dry white wine", "bottled clam broth", "baking potato", "spaghetti", "flat leaf parsley")|1536.7  |1           |5.0       |
|99      |Chaat Masala                                  |Asian         |NA      |PT25M   |PT25M    |NA            |c("cumin seeds", "fennel seeds", "garam masala", "mango powder", "black salt", "cayenne pepper", "asafoetida powder", "ginger")                                                                           |125.3   |1           |5.0       |
|117     |Blueberry Cookies                             |Drop Cookies  |PT15M   |PT4H    |PT4H15M  |48            |c("flour", "baking powder", "salt", "vegetable shortening", "sugar", "egg", "milk", "lemon zest", "blueberries")                                                                                          |58.4    |5           |5.0       |
|46      |A Jad - Cucumber Pickle                       |Vegetable     |NA      |PT25M   |PT25M    |NA            |c("rice vinegar", "haeo")                                                                                                                                                                                 |4.3     |2           |5.0       |
|52      |Cafe Cappuccino                               |Beverages     |NA      |PT5M    |PT5M     |18            |c("instant coffee", "sugar", "nonfat dry milk solid")                                                                                                                                                     |62.2    |1           |5.0       |
|109     |Butterflied Lamb with Garlic Butter           |Lamb/Sheep    |PT4H15M |PT45M   |PT5H     |4             |c("lamb", "parsley", "fresh thyme", "lemon, rind of", "garlic", "cracked black pepper", "butter", "lemon juice", "small potato", "shallots", "olive oil")                                                 |1194.6  |2           |5.0       |
+--------+----------------------------------------------+--------------+--------+--------+---------+--------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+----------+
only showing top 10 rows
+--------+-------------------------------------+--------------+--------+--------+---------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+----------+
|RecipeId|Name                                 |RecipeCategory|CookTime|PrepTime|TotalTime|RecipeServings|RecipeIngredientParts                                                                                                                                                                                                                             |Calories|review_count|avg_rating|
+--------+-------------------------------------+--------------+--------+--------+---------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+----------+
|18800   |Bowl of Red ( Texas Chili Con Carne )|One Dish Meal |PT4H    |PT30M   |PT4H30M  |8             |c("olive oil", "onion", "garlic cloves", "boneless beef chuck roast", "red chile", "ground cumin", "dried oregano", "sweet paprika", "cider vinegar", "brewed coffee", "water", "salt", "cayenne", "cornmeal", "sour cream", "cilantro", "cheese")|637.3   |2           |5.0       |
|6721    |No-Knead Cheddar Rolls               |Breads        |NA      |PT0S    |PT0S     |8             |c("unbleached flour", "active dry yeast", "active dry yeast", "sugar", "salt", "milk", "water", "butter", "unbleached flour", "cheddar cheese", "butter", "milk")                                                                                 |331.4   |1           |5.0       |
|8282    |Mustard Dipping Sauce                |Japanese      |NA      |PT0S    |PT0S     |12            |c("soy sauce", "sake", "Dijon mustard")                                                                                                                                                                                                           |5.9     |5           |5.0       |
|12622   |Jalapeno-Olive Salsa                 |Sauces        |NA      |PT15M   |PT15M    |NA            |c("tomatoes", "black olives", "green onion", "garlic", "olive oil", "red wine vinegar", "sugar")                                                                                                                                                  |488.1   |1           |5.0       |
|14479   |Apple Meringue                       |Dessert       |PT30M   |PT30M   |PT1H     |12            |c("granny smith apples", "sugar", "honey", "water", "vanilla beans", "vanilla extract", "cloves", "cinnamon", "nutmeg", "raisins", "Grand Marnier", "cognac", "sugar", "water")                                                                   |197.9   |1           |5.0       |
|14856   |M&M's Holiday Poppers                |Lunch/Snacks  |NA      |PT20M   |PT20M    |8             |"dark chocolate"                                                                                                                                                                                                                                  |79.6    |1           |5.0       |
|17464   |Baked Fish with Orange Sauce         |Very Low Carbs|PT20M   |PT5M    |PT25M    |4             |c("butter", "parsley")                                                                                                                                                                                                                            |295.5   |4           |5.0       |
|3050    |Pizzelles                            |Dessert       |NA      |PT0S    |PT0S     |NA            |c("eggs", "granulated sugar", "vanilla extract", "anise seed", "flour", "baking powder", "salt")                                                                                                                                                  |49.6    |1           |5.0       |
|13306   |Peanut Butter Crinkles               |Dessert       |PT15M   |PT30M   |PT45M    |NA            |c("margarine", "sugar", "brown sugar", "eggs", "vanilla", "unsifted flour", "baking soda", "baking powder", "salt", "sugar")                                                                                                                      |83.9    |2           |5.0       |
|6490    |Deli Brisket Bake                    |Cheese        |NA      |PT0S    |PT3H40M  |4             |c("beef brisket", "prepared mustard", "sauerkraut", "swiss cheese")                                                                                                                                                                               |1051.1  |1           |5.0       |
+--------+-------------------------------------+--------------+--------+--------+---------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+----------+
only showing top 10 rows

- `sort(F.col("avg_rating").desc())`  
  เรียงจากคะแนนเฉลี่ยมากไปน้อย

In [94]:
recipe_rating.orderBy(
    F.col("review_count").desc(),
    F.col("avg_rating").desc()
).show(10, truncate=False)

+--------+-----------------------------------------------------+--------------+--------+--------+---------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+------------------+
|RecipeId|Name                                                 |RecipeCategory|CookTime|PrepTime|TotalTime|RecipeServings|RecipeIngredientParts                                                                                                                                                                                                                                            |Calories|review_count|avg_rating        |
+--------+-----------------------------------------------------+--------------+--------+--------+---------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+------------------+
|45809   |Bourbon Chicken                                      |Chicken Breast|PT20M   |PT15M   |PT35M    |4             |c("boneless chicken breasts", "olive oil", "garlic clove", "ginger", "crushed red pepper flakes", "light brown sugar", "ketchup", "cider vinegar", "water", "soy sauce")                                                                                         |521.4   |2892        |4.314661134163209 |
|2886    |Best Banana Bread                                    |Quick Breads  |PT1H    |PT10M   |PT1H10M  |10            |c("butter", "granulated sugar", "eggs", "bananas", "all-purpose flour", "baking soda", "salt", "vanilla")                                                                                                                                                        |272.8   |2182        |4.218148487626031 |
|27208   |To Die for Crock Pot Roast                           |One Dish Meal |PT9H    |PT5M    |PT9H5M   |8             |c("beef roast", "water")                                                                                                                                                                                                                                         |295.2   |1614        |4.281908302354399 |
|89204   |Crock-Pot Chicken With Black Beans &amp; Cream Cheese|One Dish Meal |PT4H    |PT3M    |PT4H3M   |4             |c("boneless chicken breasts", "black beans", "corn", "salsa", "cream cheese")                                                                                                                                                                                    |679.2   |1584        |4.2228535353535355|
|39087   |Creamy Cajun Chicken Pasta                           |Chicken Breast|PT15M   |PT10M   |PT25M    |2             |c("boneless skinless chicken breast halves", "linguine", "Cajun Seasoning Mix", "butter", "green onion", "heavy whipping cream", "sun-dried tomatoes", "salt", "dried basil", "ground black pepper", "garlic powder", "parmesan cheese")                         |719.1   |1491        |4.538564721663313 |
|67256   |Best Ever Banana Cake With Cream Cheese Frosting     |Dessert       |PT1H    |PT15M   |PT1H15M  |16            |c("bananas", "lemon juice", "flour", "baking soda", "salt", "butter", "sugar", "eggs", "vanilla", "buttermilk", "butter", "cream cheese", "vanilla", "icing sugar", "walnuts")                                                                                   |503.5   |1359        |4.325974981604121 |
|35813   |Oatmeal Raisin Cookies                               |Drop Cookies  |PT11M   |PT15M   |PT26M    |36            |c("all-purpose flour", "baking soda", "baking powder", "kosher salt", "unsalted butter", "sugar", "dark brown sugar", "eggs", "vanilla", "oats", "raisins")                                                                                                      |188.6   |1353        |4.4368070953436805|
|54257   |Yes, Virginia There is a Great Meatloaf              |Meatloaf      |PT1H    |PT20M   |PT1H20M  |NA            |c("ground beef", "egg", "sweet onion", "table salt", "black pepper", "ketchup", "half-and-half", "apple cider vinegar", "dark brown sugar", "ketchup")                                                                                                           |493.1   |1325        |4.212830188679245 |
|22782   |Jo Mama's World Famous Spaghetti                     |Spaghetti     |PT1H    |PT20M   |PT1H20M  |NA            |c("Italian sausage", "onion", "garlic cloves", "diced tomatoes", "tomato paste", "tomato sauce", "water", "basil", "dried parsley flakes", "brown sugar", "salt", "crushed red pepper flakes", "fresh coarse ground black pepper", "red wine", "parmesan cheese")|555.9   |1273        |4.423409269442263 |
|32204   |&quot;Whatever Floats Your Boat&quot; Brownies!      |Bar Cookie    |PT25M   |PT10M   |PT35M    |16            |c("butter", "sugar", "eggs", "vanilla", "flour", "salt", "chocolate chips", "raisins", "maraschino cherry", "miniature marshmallow")                                                                                                                             |390.7   |1228        |4.521986970684039 |
+--------+-----------------------------------------------------+--------------+--------+--------+---------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+------------------+
only showing top 10 rows
+--------+-----------------------------------------------------+--------------+--------+--------+---------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+------------------+
|RecipeId|Name                                                 |RecipeCategory|CookTime|PrepTime|TotalTime|RecipeServings|RecipeIngredientParts                                                                                                                                                                                                                                            |Calories|review_count|avg_rating        |
+--------+-----------------------------------------------------+--------------+--------+--------+---------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+------------------+
|45809   |Bourbon Chicken                                      |Chicken Breast|PT20M   |PT15M   |PT35M    |4             |c("boneless chicken breasts", "olive oil", "garlic clove", "ginger", "crushed red pepper flakes", "light brown sugar", "ketchup", "cider vinegar", "water", "soy sauce")                                                                                         |521.4   |2892        |4.314661134163209 |
|2886    |Best Banana Bread                                    |Quick Breads  |PT1H    |PT10M   |PT1H10M  |10            |c("butter", "granulated sugar", "eggs", "bananas", "all-purpose flour", "baking soda", "salt", "vanilla")                                                                                                                                                        |272.8   |2182        |4.218148487626031 |
|27208   |To Die for Crock Pot Roast                           |One Dish Meal |PT9H    |PT5M    |PT9H5M   |8             |c("beef roast", "water")                                                                                                                                                                                                                                         |295.2   |1614        |4.281908302354399 |
|89204   |Crock-Pot Chicken With Black Beans &amp; Cream Cheese|One Dish Meal |PT4H    |PT3M    |PT4H3M   |4             |c("boneless chicken breasts", "black beans", "corn", "salsa", "cream cheese")                                                                                                                                                                                    |679.2   |1584        |4.2228535353535355|
|39087   |Creamy Cajun Chicken Pasta                           |Chicken Breast|PT15M   |PT10M   |PT25M    |2             |c("boneless skinless chicken breast halves", "linguine", "Cajun Seasoning Mix", "butter", "green onion", "heavy whipping cream", "sun-dried tomatoes", "salt", "dried basil", "ground black pepper", "garlic powder", "parmesan cheese")                         |719.1   |1491        |4.538564721663313 |
|67256   |Best Ever Banana Cake With Cream Cheese Frosting     |Dessert       |PT1H    |PT15M   |PT1H15M  |16            |c("bananas", "lemon juice", "flour", "baking soda", "salt", "butter", "sugar", "eggs", "vanilla", "buttermilk", "butter", "cream cheese", "vanilla", "icing sugar", "walnuts")                                                                                   |503.5   |1359        |4.325974981604121 |
|35813   |Oatmeal Raisin Cookies                               |Drop Cookies  |PT11M   |PT15M   |PT26M    |36            |c("all-purpose flour", "baking soda", "baking powder", "kosher salt", "unsalted butter", "sugar", "dark brown sugar", "eggs", "vanilla", "oats", "raisins")                                                                                                      |188.6   |1353        |4.4368070953436805|
|54257   |Yes, Virginia There is a Great Meatloaf              |Meatloaf      |PT1H    |PT20M   |PT1H20M  |NA            |c("ground beef", "egg", "sweet onion", "table salt", "black pepper", "ketchup", "half-and-half", "apple cider vinegar", "dark brown sugar", "ketchup")                                                                                                           |493.1   |1325        |4.212830188679245 |
|22782   |Jo Mama's World Famous Spaghetti                     |Spaghetti     |PT1H    |PT20M   |PT1H20M  |NA            |c("Italian sausage", "onion", "garlic cloves", "diced tomatoes", "tomato paste", "tomato sauce", "water", "basil", "dried parsley flakes", "brown sugar", "salt", "crushed red pepper flakes", "fresh coarse ground black pepper", "red wine", "parmesan cheese")|555.9   |1273        |4.423409269442263 |
|32204   |&quot;Whatever Floats Your Boat&quot; Brownies!      |Bar Cookie    |PT25M   |PT10M   |PT35M    |16            |c("butter", "sugar", "eggs", "vanilla", "flour", "salt", "chocolate chips", "raisins", "maraschino cherry", "miniature marshmallow")                                                                                                                             |390.7   |1228        |4.521986970684039 |
+--------+-----------------------------------------------------+--------------+--------+--------+---------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+------------+------------------+
only showing top 10 rows

- `orderBy(...)`  
  เรียงได้หลาย column

อันนี้จะเรียงจาก
1. เรียงจาก review เยอะสุดก่อน
2. ถ้า review เท่ากัน เรียงจาก rating สูงสุด

## 20. Cache เมื่อใช้ DataFrame ซ้ำ

In [95]:
recipe_rating.cache()
recipe_rating.count()

522517

522517

- `cache()`  
  บอก Spark ว่า DataFrame นี้อาจถูกใช้ซ้ำ ให้เก็บไว้ใน memory

- `count()`  
  เป็น Action ที่ทำให้ Spark compute จริง และเริ่ม cache ข้อมูล

เหมาะกับ DataFrame ที่ใช้ซ้ำหลายรอบ

## 21. Convert DataFrame เป็น RDD / JSON / Pandas

In [96]:
recipe_rdd = recipe_rating.rdd

- `.rdd`  
  แปลง Spark DataFrame เป็น RDD

ปัจจุบันใช้ DataFrame มากกว่า เพราะใช้งานง่ายและ Spark optimize การทำงานให้อัตโนมัติ แต่ RDD คือโครงสร้างพื้นฐานระดับล่างของ Spark ที่ควรรู้ไว้

In [97]:
recipe_rating.toJSON().first()

'{"RecipeId":148,"Name":"Bugwiches","RecipeCategory":"Lunch/Snacks","CookTime":"NA","PrepTime":"PT40M","TotalTime":"PT40M","RecipeServings":"1","RecipeIngredientParts":"c(\\"carrot\\", \\"lettuce\\", \\"cucumber\\", \\"radish\\", \\"raisins\\", \\"mayonnaise\\", \\"celery\\", \\"tuna salad\\", \\"salmon salad\\")","Calories":84.0,"review_count":1,"avg_rating":0.0}'

'{"RecipeId":148,"Name":"Bugwiches","RecipeCategory":"Lunch/Snacks","CookTime":"NA","PrepTime":"PT40M","TotalTime":"PT40M","RecipeServings":"1","RecipeIngredientParts":"c(\\"carrot\\", \\"lettuce\\", \\"cucumber\\", \\"radish\\", \\"raisins\\", \\"mayonnaise\\", \\"celery\\", \\"tuna salad\\", \\"salmon salad\\")","Calories":84.0,"review_count":1,"avg_rating":0.0}'



- `toJSON()`  
  แปลงแต่ละ row เป็น JSON string

- `first()`  
  ดู JSON แถวแรก

In [98]:
small_pandas_df = recipe_rating.limit(10).toPandas()
small_pandas_df

,RecipeId,Name,RecipeCategory,CookTime,PrepTime,TotalTime,RecipeServings,RecipeIngredientParts,Calories,review_count,avg_rating
0,148,Bugwiches,Lunch/Snacks,NA,PT40M,PT40M,1,"c(""carrot"", ""lettuce"", ""cucumber"", ""radish"", ""...",84.0,1.0,0.000000
1,463,Cappuccino Coffee Mix,Beverages,NA,PT20M,PT20M,15,"c(""instant coffee granules"", ""granulated sugar...",54.3,7.0,3.714286
2,471,Seared Salmon with Horseradish Tomato Vinaigrette,Summer,PT9M,PT1H10M,PT1H19M,6,"c(""salmon fillets"", ""canola oil"", ""butter"", ""r...",797.3,3.0,3.666667
3,496,7-Up Cake,Dessert,PT42M,PT45M,PT1H27M,12,"c(""pineapple instant pudding"", ""eggs"", ""margar...",550.2,1.0,5.000000
4,833,Hamantaschen-Cookies (Haman's Hats),Dessert,PT8M,PT0S,PT8M,NA,"c(""eggs"", ""sugar"", ""orange zest"", ""margarine"",...",89.8,2.0,2.500000
5,1580,Dutch Buttercake,Dessert,PT10M,PT35M,PT45M,10,"c(""flour"", ""baking powder"", ""sugar"", ""unsalted...",312.7,2.0,4.500000
6,1591,Grilled Lemon Chicken,Chicken Breast,PT15M,PT45M,PT1H,4,"c(""fresh lemon juice"", ""extra virgin olive oil...",123.2,4.0,4.250000
7,1959,Sylvia's Famous Spareribs,< 15 Mins,NA,PT0S,PT0S,8,"c(""salt"", ""black pepper"", ""red pepper flakes"",...",982.3,NaN,NaN
8,2122,English Cream Scones,Scones,NA,PT0S,PT0S,NA,"c(""flour"", ""sugar"", ""baking powder"", ""salt"", ""...",211.5,2.0,4.000000
9,2142,Buttery Drop Cookies,Drop Cookies,PT7M,PT0S,PT7M,NA,"c(""sugar"", ""milk"", ""egg"", ""vanilla"", ""all-purp...",60.0,1.0,5.000000

,RecipeId,Name,RecipeCategory,CookTime,PrepTime,TotalTime,RecipeServings,RecipeIngredientParts,Calories,review_count,avg_rating
0,148,Bugwiches,Lunch/Snacks,NA,PT40M,PT40M,1,"c(""carrot"", ""lettuce"", ""cucumber"", ""radish"", ""...",84.0,1.0,0.000000
1,463,Cappuccino Coffee Mix,Beverages,NA,PT20M,PT20M,15,"c(""instant coffee granules"", ""granulated sugar...",54.3,7.0,3.714286
2,471,Seared Salmon with Horseradish Tomato Vinaigrette,Summer,PT9M,PT1H10M,PT1H19M,6,"c(""salmon fillets"", ""canola oil"", ""butter"", ""r...",797.3,3.0,3.666667
3,496,7-Up Cake,Dessert,PT42M,PT45M,PT1H27M,12,"c(""pineapple instant pudding"", ""eggs"", ""margar...",550.2,1.0,5.000000
4,833,Hamantaschen-Cookies (Haman's Hats),Dessert,PT8M,PT0S,PT8M,NA,"c(""eggs"", ""sugar"", ""orange zest"", ""margarine"",...",89.8,2.0,2.500000
5,1580,Dutch Buttercake,Dessert,PT10M,PT35M,PT45M,10,"c(""flour"", ""baking powder"", ""sugar"", ""unsalted...",312.7,2.0,4.500000
6,1591,Grilled Lemon Chicken,Chicken Breast,PT15M,PT45M,PT1H,4,"c(""fresh lemon juice"", ""extra virgin olive oil...",123.2,4.0,4.250000
7,1959,Sylvia's Famous Spareribs,< 15 Mins,NA,PT0S,PT0S,8,"c(""salt"", ""black pepper"", ""red pepper flakes"",...",982.3,NaN,NaN
8,2122,English Cream Scones,Scones,NA,PT0S,PT0S,NA,"c(""flour"", ""sugar"", ""baking powder"", ""salt"", ""...",211.5,2.0,4.000000
9,2142,Buttery Drop Cookies,Drop Cookies,PT7M,PT0S,PT7M,NA,"c(""sugar"", ""milk"", ""egg"", ""vanilla"", ""all-purp...",60.0,1.0,5.000000

- `limit(10)`  
  จำกัดข้อมูลเหลือ 10 แถวก่อน

- `toPandas()`  
  ดึงข้อมูลจาก Spark มาเป็น Pandas DataFrame

## 22. Save Output เป็น Parquet / CSV / JSON

In [99]:
popular_high_rated.write.mode("overwrite").parquet(
    "output/popular_high_rated_recipes.parquet"
)

- `.write`  
  เริ่มเขียน DataFrame ออกเป็นไฟล์

- `.mode("overwrite")`  
  ถ้ามี output เดิม ให้เขียนทับ

- `.parquet(...)`  
  บันทึกเป็น Parquet format

Parquet เหมาะกับ Spark เพราะอ่านเร็วและเก็บ schema ได้

In [100]:
category_summary.write.mode("overwrite").csv(
    "output/category_summary.csv",
    header=True
)

- `.csv(...)`  
  บันทึกเป็น CSV

- `header=True`  
  ให้ไฟล์มีชื่อ column

CSV เหมาะกับการเปิดดูใน Excel หรือ Google Sheets

In [101]:
category_summary.write.mode("overwrite").json(
    "output/category_summary_json"
)

- `.json(...)`  
  บันทึก output เป็น JSON

เหมาะกับงานที่ต้องส่งต่อข้อมูลให้ระบบอื่น

## 23. Spark SQL

In [102]:
recipe_rating.createOrReplaceTempView("recipe_rating")

- `createOrReplaceTempView("recipe_rating")`  
  สร้าง temporary view จาก DataFrame

เพื่อที่หลังจากนี้สามารถใช้ SQL query กับ view นี้ได้

In [103]:
spark.sql("""
SELECT
    RecipeCategory,
    COUNT(*) AS recipe_count,
    AVG(avg_rating) AS category_avg_rating
FROM recipe_rating
GROUP BY RecipeCategory
ORDER BY recipe_count DESC
""").show(20, truncate=False)

+--------------+------------+-------------------+
|RecipeCategory|recipe_count|category_avg_rating|
+--------------+------------+-------------------+
|Dessert       |62072       |4.243649206616812  |
|Lunch/Snacks  |32586       |4.403159714035772  |
|One Dish Meal |31345       |4.281247546294448  |
|Vegetable     |27231       |4.410541816979569  |
|Breakfast     |21101       |4.353555405940917  |
|Beverages     |16076       |4.521560677502439  |
|Chicken       |13249       |4.3607588636224826 |
|Meat          |13131       |4.283458514874751  |
|Breads        |12804       |4.2486104804039    |
|Pork          |12603       |4.375726736875868  |
|Sauces        |12166       |4.384590219865782  |
|Chicken Breast|11282       |4.376158489752838  |
|Potato        |10870       |4.424074260361769  |
|Quick Breads  |10387       |4.226220343603106  |
|< 60 Mins     |9719        |4.331251186852882  |
|< 30 Mins     |9020        |4.404099383190222  |
|Cheese        |8462        |4.394971679293944  |
|Pie           |7775        |4.294356169351381  |
|Bar Cookie    |7029        |4.295598919654604  |
|Low Protein   |6663        |4.367612976980021  |
+--------------+------------+-------------------+
only showing top 20 rows
+--------------+------------+-------------------+
|RecipeCategory|recipe_count|category_avg_rating|
+--------------+------------+-------------------+
|Dessert       |62072       |4.243649206616812  |
|Lunch/Snacks  |32586       |4.403159714035772  |
|One Dish Meal |31345       |4.281247546294448  |
|Vegetable     |27231       |4.410541816979569  |
|Breakfast     |21101       |4.353555405940917  |
|Beverages     |16076       |4.521560677502439  |
|Chicken       |13249       |4.3607588636224826 |
|Meat          |13131       |4.283458514874751  |
|Breads        |12804       |4.2486104804039    |
|Pork          |12603       |4.375726736875868  |
|Sauces        |12166       |4.384590219865782  |
|Chicken Breast|11282       |4.376158489752838  |
|Potato        |10870       |4.424074260361769  |
|Quick Breads  |10387       |4.226220343603106  |
|< 60 Mins     |9719        |4.331251186852882  |
|< 30 Mins     |9020        |4.404099383190222  |
|Cheese        |8462        |4.394971679293944  |
|Pie           |7775        |4.294356169351381  |
|Bar Cookie    |7029        |4.295598919654604  |
|Low Protein   |6663        |4.367612976980021  |
+--------------+------------+-------------------+
only showing top 20 rows

- `spark.sql(...)`  
  ใช้เขียน SQL บน Spark

- `GROUP BY RecipeCategory`  
  จัดกลุ่มตาม "หมวดหมู่อาหาร"

- `COUNT(*)`  
  นับจำนวนสูตร

- `AVG(avg_rating)`  
  คำนวณคะแนนเฉลี่ยของหมวดนั้น

## 24.Execution Plan

In [104]:
popular_high_rated.explain()

== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- Sort [avg_rating#1122 DESC NULLS LAST, review_count#1121L DESC NULLS LAST], true, 0
   +- Exchange rangepartitioning(avg_rating#1122 DESC NULLS LAST, review_count#1121L DESC NULLS LAST, 200), ENSURE_REQUIREMENTS, [plan_id=3100]
      +- Filter (((isnotnull(review_count#1121L) AND isnotnull(avg_rating#1122)) AND (review_count#1121L >= 50)) AND (avg_rating#1122 >= 4.5))
         +- InMemoryTableScan [RecipeId#542, Name#1, RecipeCategory#10, CookTime#4, PrepTime#5, TotalTime#6, RecipeServings#25, RecipeIngredientParts#13, Calories#544, review_count#1121L, avg_rating#1122], [isnotnull(review_count#1121L), isnotnull(avg_rating#1122), (review_count#1121L >= 50), (avg_rating#1122 >= 4.5)]
               +- InMemoryRelation [RecipeId#542, Name#1, RecipeCategory#10, CookTime#4, PrepTime#5, TotalTime#6, RecipeServings#25, RecipeIngredientParts#13, Calories#544, review_count#1121L, avg_rating#1122], StorageLevel(disk, memory, deserialized, 1 replicas)
                     +- AdaptiveSparkPlan isFinalPlan=true
                        +- == Final Plan ==
                           ResultQueryStage 2
                           +- *(5) Project [RecipeId#542, Name#1647, RecipeCategory#1649, CookTime#1651, PrepTime#1653, TotalTime#1655, RecipeServings#1657, RecipeIngredientParts#1659, Calories#1661, review_count#1121L, avg_rating#1122]
                              +- *(5) SortMergeJoin [RecipeId#542], [RecipeId#545], LeftOuter
                                 :- SortAggregate(key=[RecipeId#542], functions=[first(Name#1, false), first(RecipeCategory#10, false), first(CookTime#4, false), first(PrepTime#5, false), first(TotalTime#6, false), first(RecipeServings#25, false), first(RecipeIngredientParts#13, false), first(Calories#544, false)])
                                 :  +- *(3) Sort [RecipeId#542 ASC NULLS FIRST], false, 0
                                 :     +- ShuffleQueryStage 0
                                 :        +- Exchange hashpartitioning(RecipeId#542, 200), ENSURE_REQUIREMENTS, [plan_id=2484]
                                 :           +- SortAggregate(key=[RecipeId#542], functions=[partial_first(Name#1, false), partial_first(RecipeCategory#10, false), partial_first(CookTime#4, false), partial_first(PrepTime#5, false), partial_first(TotalTime#6, false), partial_first(RecipeServings#25, false), partial_first(RecipeIngredientParts#13, false), partial_first(Calories#544, false)])
                                 :              +- *(1) Sort [RecipeId#542 ASC NULLS FIRST], false, 0
                                 :                 +- *(1) Project [try_cast(RecipeId#0 as int) AS RecipeId#542, Name#1, RecipeCategory#10, CookTime#4, PrepTime#5, TotalTime#6, RecipeServings#25, RecipeIngredientParts#13, try_cast(regexp_replace(Calories#16, [^0-9.], , 1) as double) AS Calories#544]
                                 :                    +- *(1) Filter atleastnnonnulls(1, try_cast(RecipeId#0 as int))
                                 :                       +- FileScan csv [RecipeId#0,Name#1,CookTime#4,PrepTime#5,TotalTime#6,RecipeCategory#10,RecipeIngredientParts#13,Calories#16,RecipeServings#25] Batched: false, DataFilters: [atleastnnonnulls(1, try_cast(RecipeId#0 as int))], Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/kaggle/input/foodcom-recipes-and-reviews/recipes.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<RecipeId:string,Name:string,CookTime:string,PrepTime:string,TotalTime:string,RecipeCategor...
                                 +- *(4) Sort [RecipeId#545 ASC NULLS FIRST], false, 0
                                    +- *(4) HashAggregate(keys=[RecipeId#545], functions=[count(1), avg(Rating#546)])
                                       +- ShuffleQueryStage 1
                                          +- Exchange hashpartitioning(RecipeId#545, 200), ENSURE_REQUIREMENTS, [plan_id=2514]
                                             +- *(2) HashAggregate(keys=[RecipeId#545], functions=[partial_count(1), partial_avg(Rating#546)])
                                                +- *(2) Project [try_cast(RecipeId#29 as int) AS RecipeId#545, try_cast(Rating#32 as double) AS Rating#546]
                                                   +- *(2) Filter ((atleastnnonnulls(2, try_cast(RecipeId#29 as int), try_cast(Rating#32 as double)) AND atleastnnonnulls(1, try_cast(RecipeId#29 as int))) AND isnotnull(try_cast(RecipeId#29 as int)))
                                                      +- FileScan csv [RecipeId#29,Rating#32] Batched: false, DataFilters: [atleastnnonnulls(2, try_cast(RecipeId#29 as int), try_cast(Rating#32 as double)), atleastnnonnul..., Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/kaggle/input/foodcom-recipes-and-reviews/reviews.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<RecipeId:string,Rating:string>
                        +- == Initial Plan ==
                           Project [RecipeId#542, Name#1647, RecipeCategory#1649, CookTime#1651, PrepTime#1653, TotalTime#1655, RecipeServings#1657, RecipeIngredientParts#1659, Calories#1661, review_count#1121L, avg_rating#1122]
                           +- SortMergeJoin [RecipeId#542], [RecipeId#545], LeftOuter
                              :- SortAggregate(key=[RecipeId#542], functions=[first(Name#1, false), first(RecipeCategory#10, false), first(CookTime#4, false), first(PrepTime#5, false), first(TotalTime#6, false), first(RecipeServings#25, false), first(RecipeIngredientParts#13, false), first(Calories#544, false)])
                              :  +- Sort [RecipeId#542 ASC NULLS FIRST], false, 0
                              :     +- Exchange hashpartitioning(RecipeId#542, 200), ENSURE_REQUIREMENTS, [plan_id=2436]
                              :        +- SortAggregate(key=[RecipeId#542], functions=[partial_first(Name#1, false), partial_first(RecipeCategory#10, false), partial_first(CookTime#4, false), partial_first(PrepTime#5, false), partial_first(TotalTime#6, false), partial_first(RecipeServings#25, false), partial_first(RecipeIngredientParts#13, false), partial_first(Calories#544, false)])
                              :           +- Sort [RecipeId#542 ASC NULLS FIRST], false, 0
                              :              +- Project [try_cast(RecipeId#0 as int) AS RecipeId#542, Name#1, RecipeCategory#10, CookTime#4, PrepTime#5, TotalTime#6, RecipeServings#25, RecipeIngredientParts#13, try_cast(regexp_replace(Calories#16, [^0-9.], , 1) as double) AS Calories#544]
                              :                 +- Filter atleastnnonnulls(1, try_cast(RecipeId#0 as int))
                              :                    +- FileScan csv [RecipeId#0,Name#1,CookTime#4,PrepTime#5,TotalTime#6,RecipeCategory#10,RecipeIngredientParts#13,Calories#16,RecipeServings#25] Batched: false, DataFilters: [atleastnnonnulls(1, try_cast(RecipeId#0 as int))], Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/kaggle/input/foodcom-recipes-and-reviews/recipes.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<RecipeId:string,Name:string,CookTime:string,PrepTime:string,TotalTime:string,RecipeCategor...
                              +- Sort [RecipeId#545 ASC NULLS FIRST], false, 0
                                 +- HashAggregate(keys=[RecipeId#545], functions=[count(1), avg(Rating#546)])
                                    +- Exchange hashpartitioning(RecipeId#545, 200), ENSURE_REQUIREMENTS, [plan_id=2439]
                                       +- HashAggregate(keys=[RecipeId#545], functions=[partial_count(1), partial_avg(Rating#546)])
                                          +- Project [try_cast(RecipeId#29 as int) AS RecipeId#545, try_cast(Rating#32 as double) AS Rating#546]
                                             +- Filter ((atleastnnonnulls(2, try_cast(RecipeId#29 as int), try_cast(Rating#32 as double)) AND atleastnnonnulls(1, try_cast(RecipeId#29 as int))) AND isnotnull(try_cast(RecipeId#29 as int)))
                                                +- FileScan csv [RecipeId#29,Rating#32] Batched: false, DataFilters: [atleastnnonnulls(2, try_cast(RecipeId#29 as int), try_cast(Rating#32 as double)), atleastnnonnul..., Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/kaggle/input/foodcom-recipes-and-reviews/reviews.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<RecipeId:string,Rating:string>


== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- Sort [avg_rating#5027 DESC NULLS LAST, review_count#5026L DESC NULLS LAST], true, 0
   +- Exchange rangepartitioning(avg_rating#5027 DESC NULLS LAST, review_count#5026L DESC NULLS LAST, 200), ENSURE_REQUIREMENTS, [plan_id=5121]
      +- Filter (((isnotnull(review_count#5026L) AND isnotnull(avg_rating#5027)) AND (review_count#5026L >= 50)) AND (avg_rating#5027 >= 4.5))
         +- InMemoryTableScan [RecipeId#4415, Name#1, RecipeCategory#10, CookTime#4, PrepTime#5, TotalTime#6, RecipeServings#25, RecipeIngredientParts#13, Calories#4417, review_count#5026L, avg_rating#5027], [isnotnull(review_count#5026L), isnotnull(avg_rating#5027), (review_count#5026L >= 50), (avg_rating#5027 >= 4.5)]
               +- InMemoryRelation [RecipeId#4415, Name#1, RecipeCategory#10, CookTime#4, PrepTime#5, TotalTime#6, RecipeServings#25, RecipeIngredientParts#13, Calories#4417, review_count#5026L, avg_rating#5027], StorageLevel(disk, memory, deserialized, 1 replicas)
                     +- AdaptiveSparkPlan isFinalPlan=true
                        +- == Final Plan ==
                           ResultQueryStage 2
                           +- *(5) Project [RecipeId#542, Name#1647, RecipeCategory#1649, CookTime#1651, PrepTime#1653, TotalTime#1655, RecipeServings#1657, RecipeIngredientParts#1659, Calories#1661, review_count#1121L, avg_rating#1122]
                              +- *(5) SortMergeJoin [RecipeId#542], [RecipeId#545], LeftOuter
                                 :- SortAggregate(key=[RecipeId#542], functions=[first(Name#1, false), first(RecipeCategory#10, false), first(CookTime#4, false), first(PrepTime#5, false), first(TotalTime#6, false), first(RecipeServings#25, false), first(RecipeIngredientParts#13, false), first(Calories#544, false)])
                                 :  +- *(3) Sort [RecipeId#542 ASC NULLS FIRST], false, 0
                                 :     +- ShuffleQueryStage 0
                                 :        +- Exchange hashpartitioning(RecipeId#542, 200), ENSURE_REQUIREMENTS, [plan_id=2484]
                                 :           +- SortAggregate(key=[RecipeId#542], functions=[partial_first(Name#1, false), partial_first(RecipeCategory#10, false), partial_first(CookTime#4, false), partial_first(PrepTime#5, false), partial_first(TotalTime#6, false), partial_first(RecipeServings#25, false), partial_first(RecipeIngredientParts#13, false), partial_first(Calories#544, false)])
                                 :              +- *(1) Sort [RecipeId#542 ASC NULLS FIRST], false, 0
                                 :                 +- *(1) Project [try_cast(RecipeId#0 as int) AS RecipeId#542, Name#1, RecipeCategory#10, CookTime#4, PrepTime#5, TotalTime#6, RecipeServings#25, RecipeIngredientParts#13, try_cast(regexp_replace(Calories#16, [^0-9.], , 1) as double) AS Calories#544]
                                 :                    +- *(1) Filter atleastnnonnulls(1, try_cast(RecipeId#0 as int))
                                 :                       +- FileScan csv [RecipeId#0,Name#1,CookTime#4,PrepTime#5,TotalTime#6,RecipeCategory#10,RecipeIngredientParts#13,Calories#16,RecipeServings#25] Batched: false, DataFilters: [atleastnnonnulls(1, try_cast(RecipeId#0 as int))], Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/kaggle/input/foodcom-recipes-and-reviews/recipes.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<RecipeId:string,Name:string,CookTime:string,PrepTime:string,TotalTime:string,RecipeCategor...
                                 +- *(4) Sort [RecipeId#545 ASC NULLS FIRST], false, 0
                                    +- *(4) HashAggregate(keys=[RecipeId#545], functions=[count(1), avg(Rating#546)])
                                       +- ShuffleQueryStage 1
                                          +- Exchange hashpartitioning(RecipeId#545, 200), ENSURE_REQUIREMENTS, [plan_id=2514]
                                             +- *(2) HashAggregate(keys=[RecipeId#545], functions=[partial_count(1), partial_avg(Rating#546)])
                                                +- *(2) Project [try_cast(RecipeId#29 as int) AS RecipeId#545, try_cast(Rating#32 as double) AS Rating#546]
                                                   +- *(2) Filter ((atleastnnonnulls(2, try_cast(RecipeId#29 as int), try_cast(Rating#32 as double)) AND atleastnnonnulls(1, try_cast(RecipeId#29 as int))) AND isnotnull(try_cast(RecipeId#29 as int)))
                                                      +- FileScan csv [RecipeId#29,Rating#32] Batched: false, DataFilters: [atleastnnonnulls(2, try_cast(RecipeId#29 as int), try_cast(Rating#32 as double)), atleastnnonnul..., Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/kaggle/input/foodcom-recipes-and-reviews/reviews.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<RecipeId:string,Rating:string>
                        +- == Initial Plan ==
                           Project [RecipeId#542, Name#1647, RecipeCategory#1649, CookTime#1651, PrepTime#1653, TotalTime#1655, RecipeServings#1657, RecipeIngredientParts#1659, Calories#1661, review_count#1121L, avg_rating#1122]
                           +- SortMergeJoin [RecipeId#542], [RecipeId#545], LeftOuter
                              :- SortAggregate(key=[RecipeId#542], functions=[first(Name#1, false), first(RecipeCategory#10, false), first(CookTime#4, false), first(PrepTime#5, false), first(TotalTime#6, false), first(RecipeServings#25, false), first(RecipeIngredientParts#13, false), first(Calories#544, false)])
                              :  +- Sort [RecipeId#542 ASC NULLS FIRST], false, 0
                              :     +- Exchange hashpartitioning(RecipeId#542, 200), ENSURE_REQUIREMENTS, [plan_id=2436]
                              :        +- SortAggregate(key=[RecipeId#542], functions=[partial_first(Name#1, false), partial_first(RecipeCategory#10, false), partial_first(CookTime#4, false), partial_first(PrepTime#5, false), partial_first(TotalTime#6, false), partial_first(RecipeServings#25, false), partial_first(RecipeIngredientParts#13, false), partial_first(Calories#544, false)])
                              :           +- Sort [RecipeId#542 ASC NULLS FIRST], false, 0
                              :              +- Project [try_cast(RecipeId#0 as int) AS RecipeId#542, Name#1, RecipeCategory#10, CookTime#4, PrepTime#5, TotalTime#6, RecipeServings#25, RecipeIngredientParts#13, try_cast(regexp_replace(Calories#16, [^0-9.], , 1) as double) AS Calories#544]
                              :                 +- Filter atleastnnonnulls(1, try_cast(RecipeId#0 as int))
                              :                    +- FileScan csv [RecipeId#0,Name#1,CookTime#4,PrepTime#5,TotalTime#6,RecipeCategory#10,RecipeIngredientParts#13,Calories#16,RecipeServings#25] Batched: false, DataFilters: [atleastnnonnulls(1, try_cast(RecipeId#0 as int))], Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/kaggle/input/foodcom-recipes-and-reviews/recipes.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<RecipeId:string,Name:string,CookTime:string,PrepTime:string,TotalTime:string,RecipeCategor...
                              +- Sort [RecipeId#545 ASC NULLS FIRST], false, 0
                                 +- HashAggregate(keys=[RecipeId#545], functions=[count(1), avg(Rating#546)])
                                    +- Exchange hashpartitioning(RecipeId#545, 200), ENSURE_REQUIREMENTS, [plan_id=2439]
                                       +- HashAggregate(keys=[RecipeId#545], functions=[partial_count(1), partial_avg(Rating#546)])
                                          +- Project [try_cast(RecipeId#29 as int) AS RecipeId#545, try_cast(Rating#32 as double) AS Rating#546]
                                             +- Filter ((atleastnnonnulls(2, try_cast(RecipeId#29 as int), try_cast(Rating#32 as double)) AND atleastnnonnulls(1, try_cast(RecipeId#29 as int))) AND isnotnull(try_cast(RecipeId#29 as int)))
                                                +- FileScan csv [RecipeId#29,Rating#32] Batched: false, DataFilters: [atleastnnonnulls(2, try_cast(RecipeId#29 as int), try_cast(Rating#32 as double)), atleastnnonnul..., Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/kaggle/input/foodcom-recipes-and-reviews/reviews.csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<RecipeId:string,Rating:string>

- `explain()`  
  ใช้ดูว่า Spark วางแผน execute งานอย่างไร

เป้าหมายเพื่อดูว่า Spark ไม่ได้ run ทีละบรรทัดทันที แต่จะสร้าง plan แล้วค่อย run ตอนเจอ Action

## 25. Scala Notes เบื้องต้น

In [105]:
# Scala note: Start SparkSession

'''
import org.apache.spark.sql.SparkSession

val spark = SparkSession.builder()
  .appName("FoodCom Spark Practice")
  .getOrCreate()
'''

'\nimport org.apache.spark.sql.SparkSession\n\nval spark = SparkSession.builder()\n  .appName("FoodCom Spark Practice")\n  .getOrCreate()\n'

'\nimport org.apache.spark.sql.SparkSession\n\nval spark = SparkSession.builder()\n  .appName("FoodCom Spark Practice")\n  .getOrCreate()\n'

In [106]:
# Scala note: Read CSV

'''
val recipesDF = spark.read
  .option("header", "true")
  .csv("recipes.csv")
'''

'\nval recipesDF = spark.read\n  .option("header", "true")\n  .csv("recipes.csv")\n'

'\nval recipesDF = spark.read\n  .option("header", "true")\n  .csv("recipes.csv")\n'

In [107]:
# Scala note: Select + Filter

'''
import spark.implicits._

val recipesSmall = recipesDF
  .select("RecipeId", "Name", "RecipeCategory", "Calories")
  .filter($"Calories" > 0)
'''

'\nimport spark.implicits._\n\nval recipesSmall = recipesDF\n  .select("RecipeId", "Name", "RecipeCategory", "Calories")\n  .filter($"Calories" > 0)\n'

'\nimport spark.implicits._\n\nval recipesSmall = recipesDF\n  .select("RecipeId", "Name", "RecipeCategory", "Calories")\n  .filter($"Calories" > 0)\n'

In [108]:
# Scala note: GroupBy + Aggregation

'''
import org.apache.spark.sql.functions._

val ratingByRecipe = reviewsDF
  .groupBy("RecipeId")
  .agg(
    count("*").alias("review_count"),
    avg("Rating").alias("avg_rating")
  )
'''

'\nimport org.apache.spark.sql.functions._\n\nval ratingByRecipe = reviewsDF\n  .groupBy("RecipeId")\n  .agg(\n    count("*").alias("review_count"),\n    avg("Rating").alias("avg_rating")\n  )\n'

'\nimport org.apache.spark.sql.functions._\n\nval ratingByRecipe = reviewsDF\n  .groupBy("RecipeId")\n  .agg(\n    count("*").alias("review_count"),\n    avg("Rating").alias("avg_rating")\n  )\n'

In [109]:
# Scala note: Join

'''
val recipeRating = recipesDF
  .join(ratingByRecipe, Seq("RecipeId"), "left")
'''

'\nval recipeRating = recipesDF\n  .join(ratingByRecipe, Seq("RecipeId"), "left")\n'

'\nval recipeRating = recipesDF\n  .join(ratingByRecipe, Seq("RecipeId"), "left")\n'

In [110]:
# Scala note: Save Output

'''
recipeRating.write
  .mode("overwrite")
  .parquet("output/recipe_rating.parquet")
'''

'\nrecipeRating.write\n  .mode("overwrite")\n  .parquet("output/recipe_rating.parquet")\n'

'\nrecipeRating.write\n  .mode("overwrite")\n  .parquet("output/recipe_rating.parquet")\n'

สรุป Scala

- `val`  
  ใช้ประกาศตัวแปรที่ reference ไม่เปลี่ยน

- `$"ColumnName"`  
  ใช้อ้างอิง column  
  ต้อง `import spark.implicits._`

- function เช่น `avg`, `count`, `col`  
  ต้อง import `org.apache.spark.sql.functions._`

อ้างอิง
1. https://www.google.com/url?q=https%3A%2F%2Fspark.apache.org%2Fdocs%2Flatest%2Fapi%2Fpython%2Freference%2Findex.html

2.   https://www.flexera.com/blog/finops/apache-spark-with-scala/#spark-and-scala%E2%80%94a-symbiotic-relationship

3.   https://blog.datath.com/cheatsheet-pyspark/?fbclid=IwZXh0bgNhZW0CMTAAAR2TIiC_f7r9Vmo9MCDbOZixubvORxw6qIQ5z0I39fDNy1mBjEXnn-EDvXo_aem_ATAWEUjdxOEBThE9Reem1QUsF8icNmdMsoBoLWrZIpN4hCRZCxV0pfvJz-qeS75PHhXe152qcd-L0qwv2-UnX7Zp#withi_kar_hold_fil_hi_pen_RDD

4. https://www.datacamp.com/community/blog/pyspark-cheat-sheet-python

5. https://www.datacamp.com/community/blog/pyspark-sql-cheat-sheet

6. https://blog.datath.com/cheatsheet-pyspark/?fbclid=IwZXh0bgNhZW0CMTAAAR2TIiC_f7r9Vmo9MCDbOZixubvORxw6qIQ5z0I39fDNy1mBjEXnn-EDvXo_aem_ATAWEUjdxOEBThE9Reem1QUsF8icNmdMsoBoLWrZIpN4hCRZCxV0pfvJz-qeS75PHhXe152qcd-L0qwv2-UnX7Zp#withi_kar_hold_fil_hi_pen_RDD